name: Publish-Module

# Trigger only on the push of a tag (no branch CI triggers)
trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: PowerShell@2
    displayName: Print Hello World
    inputs:
      targetType: inline
      script: |
        Write-Host 'Hello World'
