// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//======================================================================================================================
// Ingestion database
// Used for data ingestion, normalization, and cleansing.
//======================================================================================================================

// For allowed commands, see https://learn.microsoft.com/azure/data-explorer/database-script

//===| ActualCosts |====================================================================================================
// Supported versions:
// - C360-2025-04
//======================================================================================================================

// ActualCosts_raw table -- Create the table if it doesn't exist
.create-merge table ActualCosts_raw ( ignore: string )

// ActualCosts_raw table -- Remove all columns to allow changing column types
.alter table ActualCosts_raw ( ignore: string )

// ActualCosts_raw table -- Redefine all columns
.alter table ActualCosts_raw (
    AccountName:            string,
    AccountOwnerId:         string,
    AdditionalInfo:         string,
    AvailabilityZone:       string,
    BillingAccountId:       string, 
    BillingAccountName:     string,
    BillingCurrency:        string,
    BillingPeriodEndDate:   datetime,
    BillingPeriodStartDate: datetime,
    BillingProfileId:       string,
    BillingProfileName:     string,
    ChargeType:             string,
    ConsumedService:        string,
    CostCenter:             string,
    Cost:                   real,
    Date:                   datetime,
    EffectivePrice:         real,
    Frequency:              string,
    InvoiceSection:         string,
    InvoiceSectionId:       string,
    IsAzureCreditEligible:  bool,
    MeterCategory:          string,
    MeterId:                string,
    MeterName:              string,
    MeterRegion:            string,
    MeterSubCategory:       string,
    OfferId:                string,
    PartNumber:             string,
    PlanName:               string,
    Product:                string,
    ProductOrderId:         string,
    ProductOrderName:       string,
    PublisherName:          string,
    PublisherType:          string,
    Quantity:               real,
    ReservationId:          string,
    ReservationName:        string,
    ResourceGroup:          string,
    ResourceId:             string,
    ResourceLocation:       string,
    ResourceName:           string,
    ServiceFamily:          string,
    ServiceInfo1:           string,
    ServiceInfo2:           string,
    SubscriptionId:         string,
    SubscriptionName:       string,
    Tags:                   string,
    Term:                   string,
    UnitOfMeasure:          string,
    UnitPrice:              real
)

// ActualCosts_raw ingestion mapping
.create-or-alter table ActualCosts_raw ingestion parquet mapping "ActualCosts_raw_mapping"
```
[
    { "Column": "AccountName",            "Properties": { "Field": "AccountName" } },
    { "Column": "AccountOwnerId",         "Properties": { "Field": "AccountOwnerId" } },
    { "Column": "AdditionalInfo",         "Properties": { "Field": "AdditionalInfo" } },
    { "Column": "AvailabilityZone",       "Properties": { "Field": "AvailabilityZone" } },
    { "Column": "BillingAccountId",       "Properties": { "Field": "BillingAccountId" } },
    { "Column": "BillingAccountName",     "Properties": { "Field": "BillingAccountName" } },
    { "Column": "BillingCurrency",        "Properties": { "Field": "BillingCurrency" } },
    { "Column": "BillingPeriodEndDate",   "Properties": { "Field": "BillingPeriodEndDate" } },
    { "Column": "BillingPeriodStartDate", "Properties": { "Field": "BillingPeriodStartDate" } },
    { "Column": "BillingProfileId",       "Properties": { "Field": "BillingProfileId" } },
    { "Column": "BillingProfileName",     "Properties": { "Field": "BillingProfileName" } },
    { "Column": "ChargeType",             "Properties": { "Field": "ChargeType" } },
    { "Column": "ConsumedService",        "Properties": { "Field": "ConsumedService" } },
    { "Column": "CostCenter",             "Properties": { "Field": "CostCenter" } },
    { "Column": "Cost",                   "Properties": { "Field": "Cost" } },
    { "Column": "Date",                   "Properties": { "Field": "Date" } },
    { "Column": "EffectivePrice",         "Properties": { "Field": "EffectivePrice" } },
    { "Column": "Frequency",              "Properties": { "Field": "Frequency" } },
    { "Column": "InvoiceSection",         "Properties": { "Field": "InvoiceSection" } },
    { "Column": "InvoiceSectionId",       "Properties": { "Field": "InvoiceSectionId" } },
    { "Column": "IsAzureCreditEligible",  "Properties": { "Field": "IsAzureCreditEligible" } },
    { "Column": "MeterCategory",          "Properties": { "Field": "MeterCategory" } },
    { "Column": "MeterId",                "Properties": { "Field": "MeterId" } },
    { "Column": "MeterName",              "Properties": { "Field": "MeterName" } },
    { "Column": "MeterRegion",            "Properties": { "Field": "MeterRegion" } },
    { "Column": "MeterSubCategory",       "Properties": { "Field": "MeterSubCategory" } },
    { "Column": "OfferId",                "Properties": { "Field": "OfferId" } },
    { "Column": "PartNumber",             "Properties": { "Field": "PartNumber" } },
    { "Column": "PlanName",               "Properties": { "Field": "PlanName" } },
    { "Column": "Product",                "Properties": { "Field": "Product" } },
    { "Column": "ProductOrderId",         "Properties": { "Field": "ProductOrderId" } },
    { "Column": "ProductOrderName",       "Properties": { "Field": "ProductOrderName" } },
    { "Column": "PublisherName",          "Properties": { "Field": "PublisherName" } },
    { "Column": "PublisherType",          "Properties": { "Field": "PublisherType" } },
    { "Column": "Quantity",               "Properties": { "Field": "Quantity" } },
    { "Column": "ReservationId",          "Properties": { "Field": "ReservationId" } },
    { "Column": "ReservationName",        "Properties": { "Field": "ReservationName" } },
    { "Column": "ResourceGroup",          "Properties": { "Field": "ResourceGroup" } },
    { "Column": "ResourceId",             "Properties": { "Field": "ResourceId" } },
    { "Column": "ResourceLocation",       "Properties": { "Field": "ResourceLocation" } },
    { "Column": "ResourceName",           "Properties": { "Field": "ResourceName" } },
    { "Column": "ServiceFamily",          "Properties": { "Field": "ServiceFamily" } },
    { "Column": "ServiceInfo1",           "Properties": { "Field": "ServiceInfo1" } },
    { "Column": "ServiceInfo2",           "Properties": { "Field": "ServiceInfo2" } },
    { "Column": "SubscriptionId",         "Properties": { "Field": "SubscriptionId" } },
    { "Column": "SubscriptionName",       "Properties": { "Field": "SubscriptionName" } },
    { "Column": "Tags",                   "Properties": { "Field": "Tags" } },
    { "Column": "Term",                   "Properties": { "Field": "Term" } },
    { "Column": "UnitOfMeasure",          "Properties": { "Field": "UnitOfMeasure" } },
    { "Column": "UnitPrice",              "Properties": { "Field": "UnitPrice" } }
]
```

// ActualCosts_raw retention policy (clear historical data)
.alter-merge table ActualCosts_raw policy retention softdelete = 0d recoverability = disabled

// ActualCosts_raw retention policy (set the user-defined retention period)
.alter-merge table ActualCosts_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable ActualCosts_raw streaming ingestion (required for Fabric)
.alter table ActualCosts_raw policy streamingingestion disable


//===| AmortizedCosts |=================================================================================================
// Supported versions:
// - C360-2025-04
//======================================================================================================================

// AmortizedCosts_raw table -- Create the table if it doesn't exist
.create-merge table AmortizedCosts_raw ( ignore: string )

// AmortizedCosts_raw table -- Remove all columns to allow changing column types
.alter table AmortizedCosts_raw ( ignore: string )

// AmortizedCosts_raw table -- Redefine all columns
.alter table AmortizedCosts_raw (
    AccountName:            string,
    AccountOwnerId:         string,
    AdditionalInfo:         string,
    AvailabilityZone:       string,
    BillingAccountId:       string, 
    BillingAccountName:     string,
    BillingCurrency:        string,
    BillingPeriodEndDate:   datetime,
    BillingPeriodStartDate: datetime,
    BillingProfileId:       string,
    BillingProfileName:     string,
    ChargeType:             string,
    ConsumedService:        string,
    CostCenter:             string,
    Cost:                   real,
    Date:                   datetime,
    EffectivePrice:         real,
    Frequency:              string,
    InvoiceSection:         string,
    InvoiceSectionId:       string,
    IsAzureCreditEligible:  bool,
    MeterCategory:          string,
    MeterId:                string,
    MeterName:              string,
    MeterRegion:            string,
    MeterSubCategory:       string,
    OfferId:                string,
    PartNumber:             string,
    PlanName:               string,
    Product:                string,
    ProductOrderId:         string,
    ProductOrderName:       string,
    PublisherName:          string,
    PublisherType:          string,
    Quantity:               real,
    ReservationId:          string,
    ReservationName:        string,
    ResourceGroup:          string,
    ResourceId:             string,
    ResourceLocation:       string,
    ResourceName:           string,
    ServiceFamily:          string,
    ServiceInfo1:           string,
    ServiceInfo2:           string,
    SubscriptionId:         string,
    SubscriptionName:       string,
    Tags:                   string,
    Term:                   string,
    UnitOfMeasure:          string,
    UnitPrice:              real
)

// AmortizedCosts_raw ingestion mapping
.create-or-alter table AmortizedCosts_raw ingestion parquet mapping "AmortizedCosts_raw_mapping"
```
[
    { "Column": "AccountName",            "Properties": { "Field": "AccountName" } },
    { "Column": "AccountOwnerId",         "Properties": { "Field": "AccountOwnerId" } },
    { "Column": "AdditionalInfo",         "Properties": { "Field": "AdditionalInfo" } },
    { "Column": "AvailabilityZone",       "Properties": { "Field": "AvailabilityZone" } },
    { "Column": "BillingAccountId",       "Properties": { "Field": "BillingAccountId" } },
    { "Column": "BillingAccountName",     "Properties": { "Field": "BillingAccountName" } },
    { "Column": "BillingCurrency",        "Properties": { "Field": "BillingCurrency" } },
    { "Column": "BillingPeriodEndDate",   "Properties": { "Field": "BillingPeriodEndDate" } },
    { "Column": "BillingPeriodStartDate", "Properties": { "Field": "BillingPeriodStartDate" } },
    { "Column": "BillingProfileId",       "Properties": { "Field": "BillingProfileId" } },
    { "Column": "BillingProfileName",     "Properties": { "Field": "BillingProfileName" } },
    { "Column": "ChargeType",             "Properties": { "Field": "ChargeType" } },
    { "Column": "ConsumedService",        "Properties": { "Field": "ConsumedService" } },
    { "Column": "CostCenter",             "Properties": { "Field": "CostCenter" } },
    { "Column": "Cost",                   "Properties": { "Field": "Cost" } },
    { "Column": "Date",                   "Properties": { "Field": "Date" } },
    { "Column": "EffectivePrice",         "Properties": { "Field": "EffectivePrice" } },
    { "Column": "Frequency",              "Properties": { "Field": "Frequency" } },
    { "Column": "InvoiceSection",         "Properties": { "Field": "InvoiceSection" } },
    { "Column": "InvoiceSectionId",       "Properties": { "Field": "InvoiceSectionId" } },
    { "Column": "IsAzureCreditEligible",  "Properties": { "Field": "IsAzureCreditEligible" } },
    { "Column": "MeterCategory",          "Properties": { "Field": "MeterCategory" } },
    { "Column": "MeterId",                "Properties": { "Field": "MeterId" } },
    { "Column": "MeterName",              "Properties": { "Field": "MeterName" } },
    { "Column": "MeterRegion",            "Properties": { "Field": "MeterRegion" } },
    { "Column": "MeterSubCategory",       "Properties": { "Field": "MeterSubCategory" } },
    { "Column": "OfferId",                "Properties": { "Field": "OfferId" } },
    { "Column": "PartNumber",             "Properties": { "Field": "PartNumber" } },
    { "Column": "PlanName",               "Properties": { "Field": "PlanName" } },
    { "Column": "Product",                "Properties": { "Field": "Product" } },
    { "Column": "ProductOrderId",         "Properties": { "Field": "ProductOrderId" } },
    { "Column": "ProductOrderName",       "Properties": { "Field": "ProductOrderName" } },
    { "Column": "PublisherName",          "Properties": { "Field": "PublisherName" } },
    { "Column": "PublisherType",          "Properties": { "Field": "PublisherType" } },
    { "Column": "Quantity",               "Properties": { "Field": "Quantity" } },
    { "Column": "ReservationId",          "Properties": { "Field": "ReservationId" } },
    { "Column": "ReservationName",        "Properties": { "Field": "ReservationName" } },
    { "Column": "ResourceGroup",          "Properties": { "Field": "ResourceGroup" } },
    { "Column": "ResourceId",             "Properties": { "Field": "ResourceId" } },
    { "Column": "ResourceLocation",       "Properties": { "Field": "ResourceLocation" } },
    { "Column": "ResourceName",           "Properties": { "Field": "ResourceName" } },
    { "Column": "ServiceFamily",          "Properties": { "Field": "ServiceFamily" } },
    { "Column": "ServiceInfo1",           "Properties": { "Field": "ServiceInfo1" } },
    { "Column": "ServiceInfo2",           "Properties": { "Field": "ServiceInfo2" } },
    { "Column": "SubscriptionId",         "Properties": { "Field": "SubscriptionId" } },
    { "Column": "SubscriptionName",       "Properties": { "Field": "SubscriptionName" } },
    { "Column": "Tags",                   "Properties": { "Field": "Tags" } },
    { "Column": "Term",                   "Properties": { "Field": "Term" } },
    { "Column": "UnitOfMeasure",          "Properties": { "Field": "UnitOfMeasure" } },
    { "Column": "UnitPrice",              "Properties": { "Field": "UnitPrice" } }
]
```

// AmortizedCosts_raw retention policy (clear historical data)
.alter-merge table AmortizedCosts_raw policy retention softdelete = 0d recoverability = disabled

// AmortizedCosts_raw retention policy (set the user-defined retention period)
.alter-merge table AmortizedCosts_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable AmortizedCosts_raw streaming ingestion (required for Fabric)
.alter table AmortizedCosts_raw policy streamingingestion disable


//===| CommitmentDiscountUsage |========================================================================================
// Supported versions:
// - MS EA reservation details: 2023-03-01  -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-details-ea
// - MS MCA reservation details: 2023-03-01 -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-details-mca
//======================================================================================================================

// CommitmentDiscountUsage_raw table -- Create the table if it doesn't exist
.create-merge table CommitmentDiscountUsage_raw ( ignore: string )

// CommitmentDiscountUsage_raw table -- Remove all columns to allow changing column types
.alter table CommitmentDiscountUsage_raw ( ignore: string )

// CommitmentDiscountUsage_raw table -- Redefine all columns
.alter table CommitmentDiscountUsage_raw (
    InstanceFlexibilityGroup: string,
    InstanceFlexibilityRatio: real,
    InstanceId:               string,
    Kind:                     string,
    ReservationId:            string,
    ReservationOrderId:       string,
    ReservedHours:            real,
    SkuName:                  string,
    TotalReservedQuantity:    real,
    UsageDate:                datetime,
    UsedHours:                real,
    x_SourceName:             string,    // Hubs v1_0+
    x_SourceProvider:         string,    // Hubs v1_0+
    x_SourceType:             string,    // Hubs v1_0+
    x_SourceVersion:          string     // Hubs v1_0+
)

// CommitmentDiscountUsage_raw ingestion mapping
.create-or-alter table CommitmentDiscountUsage_raw ingestion parquet mapping "CommitmentDiscountUsage_raw_mapping"
```
[
    { "Column": "InstanceFlexibilityGroup", "Properties": { "Field": "InstanceFlexibilityGroup" } },
    { "Column": "InstanceFlexibilityRatio", "Properties": { "Field": "InstanceFlexibilityRatio" } },
    { "Column": "InstanceId",               "Properties": { "Field": "InstanceId" } },
    { "Column": "Kind",                     "Properties": { "Field": "Kind" } },
    { "Column": "ReservationId",            "Properties": { "Field": "ReservationId" } },
    { "Column": "ReservationOrderId",       "Properties": { "Field": "ReservationOrderId" } },
    { "Column": "ReservedHours",            "Properties": { "Field": "ReservedHours" } },
    { "Column": "SkuName",                  "Properties": { "Field": "SkuName" } },
    { "Column": "TotalReservedQuantity",    "Properties": { "Field": "TotalReservedQuantity" } },
    { "Column": "UsageDate",                "Properties": { "Field": "UsageDate" } },
    { "Column": "UsedHours",                "Properties": { "Field": "UsedHours" } },
    { "Column": "x_SourceName",             "Properties": { "Field": "x_SourceName" } },
    { "Column": "x_SourceProvider",         "Properties": { "Field": "x_SourceProvider" } },
    { "Column": "x_SourceType",             "Properties": { "Field": "x_SourceType" } },
    { "Column": "x_SourceVersion",          "Properties": { "Field": "x_SourceVersion" } }
]
```

// CommitmentDiscountUsage_raw retention policy (clear historical data)
.alter-merge table CommitmentDiscountUsage_raw policy retention softdelete = 0d recoverability = disabled

// CommitmentDiscountUsage_raw retention policy (set the user-defined retention period)
.alter-merge table CommitmentDiscountUsage_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable CommitmentDiscountUsage_raw streaming ingestion (required for Fabric)
.alter table CommitmentDiscountUsage_raw policy streamingingestion disable


//===| Costs |==========================================================================================================
// Supported versions:
// - MS: 1.0, 1.0-preview(v1) -- See https://aka.ms/costmgmt/exports/focus
// - AWS: 1.0                 -- See https://docs.aws.amazon.com/cur/latest/userguide/table-dictionary-focus-1-0-aws-columns.html
// - GCP: Jan-Jun 2024        -- See https://cloud.google.com/resources/google-cloud-focus?e=48754805&hl=en
//                                   Links to (Aug 2024): https://services.google.com/fh/files/misc/focus_guide_v1.pdf
//                               See also:
//                               - https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables/standard-usage
//                               - https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables/detailed-usage
// - OCI: 1.0                 -- See https://docs.oracle.com/iaas/Content/Billing/Concepts/costusagereportsoverview.htm#costreports__focus-cost-report-schema
// - Tencent: 1.0             -- See https://www.tencentcloud.com/document/product/555/67495 / https://www.tencentcloud.com/document/product/555/67496
// - Alibaba: 1.0             -- See https://www.alibabacloud.com/help/en/user-center/user-guide/export-alibaba-cloud-standard-billing-focus
//
// Support for non-Azure data is limited to ingestion only. Data is not transformed across versions.
//======================================================================================================================

// Costs_raw table -- Create the table if it doesn't exist
.create-merge table Costs_raw ( ignore: string )

// Costs_raw table -- Remove all columns to allow changing column types
.alter table Costs_raw ( ignore: string )

// Costs_raw table -- Redefine all columns
.alter table Costs_raw (
    AvailabilityZone:           string,    // FOCUS 0.5+
    BilledCost:                 real,      // FOCUS 0.5+
    BillingAccountId:           string,    // FOCUS 0.5+
    BillingAccountName:         string,    // FOCUS 0.5+
    BillingAccountType:         string,    // Azure 1.0-preview(v1)+
    BillingCurrency:            string,    // FOCUS 0.5+
    BillingPeriodEnd:           datetime,  // FOCUS 0.5+
    BillingPeriodStart:         datetime,  // FOCUS 0.5+
    CapacityReservationId:      string,    // FOCUS 1.1+
    CapacityReservationStatus:  string,    // FOCUS 1.1+
    ChargeCategory:             string,    // FOCUS 1.0-preview+
    ChargeClass:                string,    // FOCUS 1.0+
    ChargeDescription:          string,    // FOCUS 1.0+
    ChargeFrequency:            string,    // FOCUS 1.0+
    ChargePeriodEnd:            datetime,  // FOCUS 0.5+
    ChargePeriodStart:          datetime,  // FOCUS 0.5+
    ChargeSubcategory:          string,    // FOCUS 1.0-preview only
    CommitmentDiscountCategory: string,    // FOCUS 1.0-preview+
    CommitmentDiscountId:       string,    // FOCUS 1.0-preview+
    CommitmentDiscountName:     string,    // FOCUS 1.0-preview+
    CommitmentDiscountQuantity: real,      // FOCUS 1.1+
    CommitmentDiscountStatus:   string,    // FOCUS 1.0+
    CommitmentDiscountType:     string,    // FOCUS 1.0-preview+
    CommitmentDiscountUnit:     string,    // FOCUS 1.1+
    ConsumedQuantity:           real,      // FOCUS 1.0+
    ConsumedUnit:               string,    // FOCUS 1.0+
    ContractedCost:             real,      // FOCUS 1.0+
    ContractedUnitPrice:        real,      // FOCUS 1.0+
    EffectiveCost:              real,      // FOCUS 1.0-preview+
    InvoiceId:                  string,    // FOCUS 1.2+
    InvoiceIssuerName:          string,    // FOCUS 0.5+
    ListCost:                   real,      // FOCUS 1.0-preview+
    ListUnitPrice:              real,      // FOCUS 1.0-preview+
    PricingCategory:            string,    // FOCUS 1.0-preview+
    PricingCurrency:            string,    // FOCUS 1.2+
    PricingQuantity:            real,      // FOCUS 1.0-preview+
    PricingUnit:                string,    // FOCUS 1.0-preview+
    ProviderName:               string,    // FOCUS 0.5+
    PublisherName:              string,    // FOCUS 0.5+
    Region:                     string,    // FOCUS 0.5-1.0-preview (deprecated)
    RegionId:                   string,    // FOCUS 1.0+
    RegionName:                 string,    // FOCUS 1.0+
    ResourceId:                 string,    // FOCUS 0.5+
    ResourceName:               string,    // FOCUS 0.5+
    ResourceType:               string,    // FOCUS 1.0-preview+
    ServiceCategory:            string,    // FOCUS 0.5+
    ServiceName:                string,    // FOCUS 0.5+
    ServiceSubcategory:         string,    // FOCUS 1.1+
    SkuId:                      string,    // FOCUS 1.0-preview+
    SkuMeter:                   string,    // FOCUS 1.1+
    SkuPriceDetails:            string,    // FOCUS 1.1+
    SkuPriceId:                 string,    // FOCUS 1.0-preview+
    SubAccountId:               string,    // FOCUS 0.5+
    SubAccountName:             string,    // FOCUS 0.5+
    SubAccountType:             string,    // Azure 1.0-preview(v1)+
    Tags:                       string,    // FOCUS 1.0-preview+
    UsageAmount:                real,      // GCP Jan 2024 -- Removed Mar 2024 (UsageQuantity)
    UsageQuantity:              real,      // FOCUS 1.0-preview only
    UsageUnit:                  string,    // FOCUS 1.0-preview only
    x_AccountId:                string,    // Azure 1.0-preview(v1)+
    x_AccountName:              string,    // Azure 1.0-preview(v1)+
    x_AccountOwnerId:           string,    // Azure 1.0-preview(v1)+
    x_AmortizationClass:        string,    // Azure 1.2-preview+
    x_BilledCostInUsd:          real,      // Azure 1.0-preview(v1)+
    x_BilledUnitPrice:          real,      // Azure 1.0-preview(v1)+
    x_BillingAccountId:         string,    // Azure 1.0-preview(v1)+
    x_BillingAccountName:       string,    // Azure 1.0-preview(v1)+
    x_BillingExchangeRate:      real,      // Azure 1.0-preview(v1)+
    x_BillingExchangeRateDate:  datetime,  // Azure 1.0-preview(v1)+
    x_BillingItemCode:          string,    // Alibaba 1.0+
    x_BillingItemName:          string,    // Alibaba 1.0+
    x_BillingProfileId:         string,    // Azure 1.0-preview(v1)+
    x_BillingProfileName:       string,    // Azure 1.0-preview(v1)+
    x_ChargeId:                 string,    // Azure 1.0-preview(v1) only
    x_CommodityCode:            string,    // Alibaba 1.0+
    x_CommodityName:            string,    // Alibaba 1.0+
    x_ComponentName:            string,    // Tencent 1.0+
    x_ComponentType:            string,    // Tencent 1.0+
    x_ContractedCostInUsd:      real,      // Azure 1.0+
    x_Cost:                     real,      // GCP Jan 2024 -- Removed Jun 2024 (ContractedCost)
    x_CostAllocationRuleName:   string,    // Azure 1.0-preview(v1)+
    x_CostCategories:           string,    // AWS 1.0 (JSON)
    x_CostCenter:               string,    // Azure 1.0-preview(v1)+
    x_CostType:                 string,    // GCP Jan 2024
    x_Credits:                  string,    // GCP Jan 2024
    x_CurrencyConversionRate:   real,      // GCP Jun 2024
    x_CustomerId:               string,    // Azure 1.0-preview(v1)+
    x_CustomerName:             string,    // Azure 1.0-preview(v1)+
    x_Discount:                 string,    // AWS 1.0 (JSON)
    x_EffectiveCostInUsd:       real,      // Azure 1.0-preview(v1)+
    x_EffectiveUnitPrice:       real,      // Azure 1.0-preview(v1)+
    x_ExportTime:               datetime,  // GCP Jan 2024 / Tencent 1.0+
    x_InstanceID:               string,    // Alibaba 1.0+
    x_InvoiceId:                string,    // Azure 1.0-preview(v1)+
    x_InvoiceIssuerId:          string,    // Azure 1.0-preview(v1)+
    x_InvoiceSectionId:         string,    // Azure 1.0-preview(v1)+
    x_InvoiceSectionName:       string,    // Azure 1.0-preview(v1)+
    x_ListCostInUsd:            real,      // Azure 1.0-preview(v1)+
    x_Location:                 string,    // GCP Jan 2024
    x_OnDemandCost:             real,      // Azure 1.0-preview(v1) only
    x_OnDemandCostInUsd:        real,      // Azure 1.0-preview(v1) only
    x_OnDemandUnitPrice:        real,      // Azure 1.0-preview(v1) only
    x_Operation:                string,    // AWS 1.0
    x_OwnerAccountID:           string,    // Tencent 1.0+
    x_PartnerCreditApplied:     string,    // Azure 1.0-preview(v1)+
    x_PartnerCreditRate:        string,    // Azure 1.0-preview(v1)+
    x_PricingBlockSize:         real,      // Azure 1.0-preview(v1)+
    x_PricingCurrency:          string,    // Azure 1.0-preview(v1)-1.0r2
    x_PricingSubcategory:       string,    // Azure 1.0-preview(v1)+
    x_PricingUnitDescription:   string,    // Azure 1.0-preview(v1)+
    x_Project:                  string,    // GCP Jan 2024
    x_PublisherCategory:        string,    // Azure 1.0-preview(v1)+
    x_PublisherId:              string,    // Azure 1.0-preview(v1)+
    x_ResellerId:               string,    // Azure 1.0-preview(v1)+
    x_ResellerName:             string,    // Azure 1.0-preview(v1)+
    x_ResourceGroupName:        string,    // Azure 1.0-preview(v1)+
    x_ResourceType:             string,    // Azure 1.0-preview(v1)+
    x_ServiceCode:              string,    // AWS 1.0
    x_ServiceId:                string,    // GCP Jan 2024
    x_ServiceModel:             string,    // Azure 1.2-preview+
    x_ServicePeriodEnd:         datetime,  // Azure 1.0-preview(v1)+
    x_ServicePeriodStart:       datetime,  // Azure 1.0-preview(v1)+
    x_SkuDescription:           string,    // Azure 1.0-preview(v1)+
    x_SkuDetails:               string,    // Azure 1.0-preview(v1)-1.2-preview
    x_SkuIsCreditEligible:      bool,      // Azure 1.0-preview(v1)+
    x_SkuMeterCategory:         string,    // Azure 1.0-preview(v1)+
    x_SkuMeterId:               string,    // Azure 1.0-preview(v1)+
    x_SkuMeterName:             string,    // Azure 1.0-preview(v1)-1.0r2
    x_SkuMeterSubcategory:      string,    // Azure 1.0-preview(v1)+
    x_SkuOfferId:               string,    // Azure 1.0-preview(v1)+
    x_SkuOrderId:               string,    // Azure 1.0-preview(v1)+
    x_SkuOrderName:             string,    // Azure 1.0-preview(v1)+
    x_SkuPartNumber:            string,    // Azure 1.0-preview(v1)+
    x_SkuPlanName:              string,    // Azure 1.2-preview+
    x_SkuRegion:                string,    // Azure 1.0-preview(v1)+
    x_SkuServiceFamily:         string,    // Azure 1.0-preview(v1)+
    x_SkuTerm:                  int,       // Azure 1.0-preview(v1)+
    x_SkuTier:                  string,    // Azure 1.0-preview(v1)+
    x_SourceName:               string,    // Hubs v1_0+
    x_SourceProvider:           string,    // Hubs v1_0+
    x_SourceType:               string,    // Hubs v1_0+
    x_SourceVersion:            string,    // Hubs v1_0+
    x_SubproductName:           string,    // Tencent 1.0+ // cSpell:ignore Subproduct
    x_UsageType:                string     // AWS 1.0
)

// Costs_raw ingestion mapping
.create-or-alter table Costs_raw ingestion parquet mapping "Costs_raw_mapping"
```
[
    { "Column": "AvailabilityZone",           "Properties": { "Field": "AvailabilityZone" } },
    { "Column": "BilledCost",                 "Properties": { "Field": "BilledCost" } },
    { "Column": "BillingAccountId",           "Properties": { "Field": "BillingAccountId" } },
    { "Column": "BillingAccountName",         "Properties": { "Field": "BillingAccountName" } },
    { "Column": "BillingAccountType",         "Properties": { "Field": "BillingAccountType" } },
    { "Column": "BillingCurrency",            "Properties": { "Field": "BillingCurrency" } },
    { "Column": "BillingPeriodEnd",           "Properties": { "Field": "BillingPeriodEnd" } },
    { "Column": "BillingPeriodStart",         "Properties": { "Field": "BillingPeriodStart" } },
    { "Column": "CapacityReservationId",      "Properties": { "Field": "CapacityReservationId" } },
    { "Column": "CapacityReservationStatus",  "Properties": { "Field": "CapacityReservationStatus" } },
    { "Column": "ChargeCategory",             "Properties": { "Field": "ChargeCategory" } },
    { "Column": "ChargeClass",                "Properties": { "Field": "ChargeClass" } },
    { "Column": "ChargeDescription",          "Properties": { "Field": "ChargeDescription" } },
    { "Column": "ChargeFrequency",            "Properties": { "Field": "ChargeFrequency" } },
    { "Column": "ChargePeriodEnd",            "Properties": { "Field": "ChargePeriodEnd" } },
    { "Column": "ChargePeriodStart",          "Properties": { "Field": "ChargePeriodStart" } },
    { "Column": "ChargeSubcategory",          "Properties": { "Field": "ChargeSubcategory" } },
    { "Column": "CommitmentDiscountCategory", "Properties": { "Field": "CommitmentDiscountCategory" } },
    { "Column": "CommitmentDiscountId",       "Properties": { "Field": "CommitmentDiscountId" } },
    { "Column": "CommitmentDiscountName",     "Properties": { "Field": "CommitmentDiscountName" } },
    { "Column": "CommitmentDiscountQuantity", "Properties": { "Field": "CommitmentDiscountQuantity" } },
    { "Column": "CommitmentDiscountStatus",   "Properties": { "Field": "CommitmentDiscountStatus" } },
    { "Column": "CommitmentDiscountType",     "Properties": { "Field": "CommitmentDiscountType" } },
    { "Column": "CommitmentDiscountUnit",     "Properties": { "Field": "CommitmentDiscountUnit" } },
    { "Column": "ConsumedQuantity",           "Properties": { "Field": "ConsumedQuantity" } },
    { "Column": "ConsumedUnit",               "Properties": { "Field": "ConsumedUnit" } },
    { "Column": "ContractedCost",             "Properties": { "Field": "ContractedCost" } },
    { "Column": "ContractedUnitPrice",        "Properties": { "Field": "ContractedUnitPrice" } },
    { "Column": "EffectiveCost",              "Properties": { "Field": "EffectiveCost" } },
    { "Column": "InvoiceId",                  "Properties": { "Field": "InvoiceId" } },
    { "Column": "InvoiceIssuerName",          "Properties": { "Field": "InvoiceIssuerName" } },
    { "Column": "ListCost",                   "Properties": { "Field": "ListCost" } },
    { "Column": "ListUnitPrice",              "Properties": { "Field": "ListUnitPrice" } },
    { "Column": "PricingCategory",            "Properties": { "Field": "PricingCategory" } },
    { "Column": "PricingCurrency",            "Properties": { "Field": "PricingCurrency" } },
    { "Column": "PricingQuantity",            "Properties": { "Field": "PricingQuantity" } },
    { "Column": "PricingUnit",                "Properties": { "Field": "PricingUnit" } },
    { "Column": "ProviderName",               "Properties": { "Field": "ProviderName" } },
    { "Column": "PublisherName",              "Properties": { "Field": "PublisherName" } },
    { "Column": "Region",                     "Properties": { "Field": "Region" } },
    { "Column": "RegionId",                   "Properties": { "Field": "RegionId" } },
    { "Column": "RegionName",                 "Properties": { "Field": "RegionName" } },
    { "Column": "ResourceId",                 "Properties": { "Field": "ResourceId" } },
    { "Column": "ResourceName",               "Properties": { "Field": "ResourceName" } },
    { "Column": "ResourceType",               "Properties": { "Field": "ResourceType" } },
    { "Column": "ServiceCategory",            "Properties": { "Field": "ServiceCategory" } },
    { "Column": "ServiceName",                "Properties": { "Field": "ServiceName" } },
    { "Column": "ServiceSubcategory",         "Properties": { "Field": "ServiceSubcategory" } },
    { "Column": "SkuId",                      "Properties": { "Field": "SkuId" } },
    { "Column": "SkuMeter",                   "Properties": { "Field": "SkuMeter" } },
    { "Column": "SkuPriceDetails",            "Properties": { "Field": "SkuPriceDetails" } },
    { "Column": "SkuPriceId",                 "Properties": { "Field": "SkuPriceId" } },
    { "Column": "SubAccountId",               "Properties": { "Field": "SubAccountId" } },
    { "Column": "SubAccountName",             "Properties": { "Field": "SubAccountName" } },
    { "Column": "SubAccountType",             "Properties": { "Field": "SubAccountType" } },
    { "Column": "Tags",                       "Properties": { "Field": "Tags" } },
    { "Column": "UsageAmount",                "Properties": { "Field": "UsageAmount" } },
    { "Column": "UsageQuantity",              "Properties": { "Field": "UsageQuantity" } },
    { "Column": "UsageUnit",                  "Properties": { "Field": "UsageUnit" } },
    { "Column": "x_AccountId",                "Properties": { "Field": "x_AccountId" } },
    { "Column": "x_AccountName",              "Properties": { "Field": "x_AccountName" } },
    { "Column": "x_AccountOwnerId",           "Properties": { "Field": "x_AccountOwnerId" } },
    { "Column": "x_AmortizationClass",        "Properties": { "Field": "x_AmortizationClass" } },
    { "Column": "x_BilledCostInUsd",          "Properties": { "Field": "x_BilledCostInUsd" } },
    { "Column": "x_BilledUnitPrice",          "Properties": { "Field": "x_BilledUnitPrice" } },
    { "Column": "x_BillingAccountId",         "Properties": { "Field": "x_BillingAccountId" } },
    { "Column": "x_BillingAccountName",       "Properties": { "Field": "x_BillingAccountName" } },
    { "Column": "x_BillingExchangeRate",      "Properties": { "Field": "x_BillingExchangeRate" } },
    { "Column": "x_BillingExchangeRateDate",  "Properties": { "Field": "x_BillingExchangeRateDate" } },
    { "Column": "x_BillingItemCode",          "Properties": { "Field": "x_BillingItemCode" } },
    { "Column": "x_BillingItemName",          "Properties": { "Field": "x_BillingItemName" } },
    { "Column": "x_BillingProfileId",         "Properties": { "Field": "x_BillingProfileId" } },
    { "Column": "x_BillingProfileName",       "Properties": { "Field": "x_BillingProfileName" } },
    { "Column": "x_ChargeId",                 "Properties": { "Field": "x_ChargeId" } },
    { "Column": "x_ContractedCostInUsd",      "Properties": { "Field": "x_ContractedCostInUsd" } },
    { "Column": "x_CommodityCode",            "Properties": { "Field": "x_CommodityCode" } },
    { "Column": "x_CommodityName",            "Properties": { "Field": "x_CommodityName" } },
    { "Column": "x_ComponentName",            "Properties": { "Field": "x_ComponentName" } },
    { "Column": "x_ComponentType",            "Properties": { "Field": "x_ComponentType" } },
    { "Column": "x_Cost",                     "Properties": { "Field": "x_Cost" } },
    { "Column": "x_CostAllocationRuleName",   "Properties": { "Field": "x_CostAllocationRuleName" } },
    { "Column": "x_CostCategories",           "Properties": { "Field": "x_CostCategories" } },
    { "Column": "x_CostCenter",               "Properties": { "Field": "x_CostCenter" } },
    { "Column": "x_Credits",                  "Properties": { "Field": "x_Credits" } },
    { "Column": "x_CostType",                 "Properties": { "Field": "x_CostType" } },
    { "Column": "x_CurrencyConversionRate",   "Properties": { "Field": "x_CurrencyConversionRate" } },
    { "Column": "x_CustomerId",               "Properties": { "Field": "x_CustomerId" } },
    { "Column": "x_CustomerName",             "Properties": { "Field": "x_CustomerName" } },
    { "Column": "x_Discount",                 "Properties": { "Field": "x_Discount" } },
    { "Column": "x_EffectiveCostInUsd",       "Properties": { "Field": "x_EffectiveCostInUsd" } },
    { "Column": "x_EffectiveUnitPrice",       "Properties": { "Field": "x_EffectiveUnitPrice" } },
    { "Column": "x_ExportTime",               "Properties": { "Field": "x_ExportTime" } },
    { "Column": "x_InstanceID",               "Properties": { "Field": "x_InstanceID" } },
    { "Column": "x_InvoiceId",                "Properties": { "Field": "x_InvoiceId" } },
    { "Column": "x_InvoiceIssuerId",          "Properties": { "Field": "x_InvoiceIssuerId" } },
    { "Column": "x_InvoiceSectionId",         "Properties": { "Field": "x_InvoiceSectionId" } },
    { "Column": "x_InvoiceSectionName",       "Properties": { "Field": "x_InvoiceSectionName" } },
    { "Column": "x_ListCostInUsd",            "Properties": { "Field": "x_ListCostInUsd" } },
    { "Column": "x_Location",                 "Properties": { "Field": "x_Location" } },
    { "Column": "x_OnDemandCost",             "Properties": { "Field": "x_OnDemandCost" } },
    { "Column": "x_OnDemandCostInUsd",        "Properties": { "Field": "x_OnDemandCostInUsd" } },
    { "Column": "x_OnDemandUnitPrice",        "Properties": { "Field": "x_OnDemandUnitPrice" } },
    { "Column": "x_Operation",                "Properties": { "Field": "x_Operation" } },
    { "Column": "x_OwnerAccountID",           "Properties": { "Field": "x_OwnerAccountID" } },
    { "Column": "x_PartnerCreditApplied",     "Properties": { "Field": "x_PartnerCreditApplied" } },
    { "Column": "x_PartnerCreditRate",        "Properties": { "Field": "x_PartnerCreditRate" } },
    { "Column": "x_PricingBlockSize",         "Properties": { "Field": "x_PricingBlockSize" } },
    { "Column": "x_PricingCurrency",          "Properties": { "Field": "x_PricingCurrency" } },
    { "Column": "x_PricingSubcategory",       "Properties": { "Field": "x_PricingSubcategory" } },
    { "Column": "x_PricingUnitDescription",   "Properties": { "Field": "x_PricingUnitDescription" } },
    { "Column": "x_Project",                  "Properties": { "Field": "x_Project" } },
    { "Column": "x_PublisherCategory",        "Properties": { "Field": "x_PublisherCategory" } },
    { "Column": "x_PublisherId",              "Properties": { "Field": "x_PublisherId" } },
    { "Column": "x_ResellerId",               "Properties": { "Field": "x_ResellerId" } },
    { "Column": "x_ResellerName",             "Properties": { "Field": "x_ResellerName" } },
    { "Column": "x_ResourceGroupName",        "Properties": { "Field": "x_ResourceGroupName" } },
    { "Column": "x_ResourceType",             "Properties": { "Field": "x_ResourceType" } },
    { "Column": "x_ServiceCode",              "Properties": { "Field": "x_ServiceCode" } },
    { "Column": "x_ServiceId",                "Properties": { "Field": "x_ServiceId" } },
    { "Column": "x_ServiceModel",             "Properties": { "Field": "x_ServiceModel" } },
    { "Column": "x_ServicePeriodEnd",         "Properties": { "Field": "x_ServicePeriodEnd" } },
    { "Column": "x_ServicePeriodStart",       "Properties": { "Field": "x_ServicePeriodStart" } },
    { "Column": "x_SkuDescription",           "Properties": { "Field": "x_SkuDescription" } },
    { "Column": "x_SkuDetails",               "Properties": { "Field": "x_SkuDetails" } },
    { "Column": "x_SkuIsCreditEligible",      "Properties": { "Field": "x_SkuIsCreditEligible" } },
    { "Column": "x_SkuMeterCategory",         "Properties": { "Field": "x_SkuMeterCategory" } },
    { "Column": "x_SkuMeterId",               "Properties": { "Field": "x_SkuMeterId" } },
    { "Column": "x_SkuMeterName",             "Properties": { "Field": "x_SkuMeterName" } },
    { "Column": "x_SkuMeterSubcategory",      "Properties": { "Field": "x_SkuMeterSubcategory" } },
    { "Column": "x_SkuOfferId",               "Properties": { "Field": "x_SkuOfferId" } },
    { "Column": "x_SkuOrderId",               "Properties": { "Field": "x_SkuOrderId" } },
    { "Column": "x_SkuOrderName",             "Properties": { "Field": "x_SkuOrderName" } },
    { "Column": "x_SkuPartNumber",            "Properties": { "Field": "x_SkuPartNumber" } },
    { "Column": "x_SkuPlanName",              "Properties": { "Field": "x_SkuPlanName" } },
    { "Column": "x_SkuRegion",                "Properties": { "Field": "x_SkuRegion" } },
    { "Column": "x_SkuServiceFamily",         "Properties": { "Field": "x_SkuServiceFamily" } },
    { "Column": "x_SkuTerm",                  "Properties": { "Field": "x_SkuTerm" } },
    { "Column": "x_SkuTier",                  "Properties": { "Field": "x_SkuTier" } },
    { "Column": "x_SourceName",               "Properties": { "Field": "x_SourceName" } },
    { "Column": "x_SourceProvider",           "Properties": { "Field": "x_SourceProvider" } },
    { "Column": "x_SourceType",               "Properties": { "Field": "x_SourceType" } },
    { "Column": "x_SourceVersion",            "Properties": { "Field": "x_SourceVersion" } },
    { "Column": "x_SubproductName",           "Properties": { "Field": "x_SubproductName" } },
    { "Column": "x_UsageType",                "Properties": { "Field": "x_UsageType" } }
]
```

// Costs_raw retention policy (clear historical data)
.alter-merge table Costs_raw policy retention softdelete = 0d recoverability = disabled

// Costs_raw retention policy (set the user-defined retention period)
.alter-merge table Costs_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable Costs_raw streaming ingestion (required for Fabric)
.alter table Costs_raw policy streamingingestion disable


//===| Prices |=========================================================================================================
// NOTE: Must be before cost details.
//
// Supported versions:
// - MS EA 2023-05-01  -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/price-sheet-ea
// - MS MCA 2023-05-01 -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/price-sheet-mca
//======================================================================================================================

// Prices_raw table -- Create the table if it doesn't exist
.create-merge table Prices_raw ( ignore: string )

// Prices_raw table -- Remove all columns to allow changing column types
.alter table Prices_raw ( ignore: string )

// Prices_raw table -- Redefine all columns
.alter table Prices_raw (
    BasePrice:          real,     // Azure EA + MCA
    BillingAccountId:   string,   // Azure MCA
    BillingAccountName: string,   // Azure MCA
    BillingCurrency:    string,   // Azure MCA
    BillingProfileId:   string,   // Azure MCA
    BillingProfileName: string,   // Azure MCA
    Currency:           string,   // Azure MCA
    CurrencyCode:       string,   // Azure EA
    EffectiveEndDate:   datetime, // Azure MCA
    EffectiveStartDate: datetime, // Azure EA + MCA
    EnrollmentNumber:   string,   // Azure EA
    IncludedQuantity:   real,     // Azure EA
    MarketPrice:        real,     // Azure EA + MCA
    MeterCategory:      string,   // Azure EA + MCA
    MeterId:            string,   // Azure MCA
    MeterID:            string,   // Azure EA
    MeterName:          string,   // Azure EA + MCA
    MeterRegion:        string,   // Azure EA + MCA
    MeterSubCategory:   string,   // Azure EA + MCA
    MeterType:          string,   // Azure EA + MCA
    OfferID:            string,   // Azure EA
    PartNumber:         string,   // Azure EA
    PriceType:          string,   // Azure EA + MCA
    Product:            string,   // Azure EA + MCA
    ProductId:          string,   // Azure MCA
    ProductID:          string,   // Azure EA
    ServiceFamily:      string,   // Azure EA + MCA
    SkuId:              string,   // Azure MCA
    SkuID:              string,   // Azure EA
    Term:               string,   // Azure EA + MCA
    TierMinimumUnits:   real,     // Azure MCA
    UnitOfMeasure:      string,   // Azure EA + MCA
    UnitPrice:          real,     // Azure EA + MCA
    x_SourceName:       string,   // Hubs v1_0+
    x_SourceProvider:   string,   // Hubs v1_0+
    x_SourceType:       string,   // Hubs v1_0+
    x_SourceVersion:    string    // Hubs v1_0+
)

// Prices_raw ingestion mapping
.create-or-alter table Prices_raw ingestion parquet mapping "Prices_raw_mapping"
```
[
    { "Column": "BasePrice",          "Properties": { "Field": "BasePrice" } },
    { "Column": "BillingAccountId",   "Properties": { "Field": "BillingAccountId" } },
    { "Column": "BillingAccountName", "Properties": { "Field": "BillingAccountName" } },
    { "Column": "BillingCurrency",    "Properties": { "Field": "BillingCurrency" } },
    { "Column": "BillingProfileId",   "Properties": { "Field": "BillingProfileId" } },
    { "Column": "BillingProfileName", "Properties": { "Field": "BillingProfileName" } },
    { "Column": "Currency",           "Properties": { "Field": "Currency" } },
    { "Column": "CurrencyCode",       "Properties": { "Field": "CurrencyCode" } },
    { "Column": "EffectiveEndDate",   "Properties": { "Field": "EffectiveEndDate" } },
    { "Column": "EffectiveStartDate", "Properties": { "Field": "EffectiveStartDate" } },
    { "Column": "EnrollmentNumber",   "Properties": { "Field": "EnrollmentNumber" } },
    { "Column": "IncludedQuantity",   "Properties": { "Field": "IncludedQuantity" } },
    { "Column": "MarketPrice",        "Properties": { "Field": "MarketPrice" } },
    { "Column": "MeterCategory",      "Properties": { "Field": "MeterCategory" } },
    { "Column": "MeterId",            "Properties": { "Field": "MeterId" } },
    { "Column": "MeterID",            "Properties": { "Field": "MeterID" } },
    { "Column": "MeterName",          "Properties": { "Field": "MeterName" } },
    { "Column": "MeterRegion",        "Properties": { "Field": "MeterRegion" } },
    { "Column": "MeterSubCategory",   "Properties": { "Field": "MeterSubCategory" } },
    { "Column": "MeterType",          "Properties": { "Field": "MeterType" } },
    { "Column": "OfferID",            "Properties": { "Field": "OfferID" } },
    { "Column": "PartNumber",         "Properties": { "Field": "PartNumber" } },
    { "Column": "PriceType",          "Properties": { "Field": "PriceType" } },
    { "Column": "Product",            "Properties": { "Field": "Product" } },
    { "Column": "ProductId",          "Properties": { "Field": "ProductId" } },
    { "Column": "ProductID",          "Properties": { "Field": "ProductID" } },
    { "Column": "ServiceFamily",      "Properties": { "Field": "ServiceFamily" } },
    { "Column": "SkuId",              "Properties": { "Field": "SkuId" } },
    { "Column": "SkuID",              "Properties": { "Field": "SkuID" } },
    { "Column": "Term",               "Properties": { "Field": "Term" } },
    { "Column": "TierMinimumUnits",   "Properties": { "Field": "TierMinimumUnits" } },
    { "Column": "UnitOfMeasure",      "Properties": { "Field": "UnitOfMeasure" } },
    { "Column": "UnitPrice",          "Properties": { "Field": "UnitPrice" } },
    { "Column": "x_SourceName",       "Properties": { "Field": "x_SourceName" } },
    { "Column": "x_SourceProvider",   "Properties": { "Field": "x_SourceProvider" } },
    { "Column": "x_SourceType",       "Properties": { "Field": "x_SourceType" } },
    { "Column": "x_SourceVersion",    "Properties": { "Field": "x_SourceVersion" } }
]
```

// Prices_raw retention policy (clear historical data)
.alter-merge table Prices_raw policy retention softdelete = 0d recoverability = disabled

// Prices_raw retention policy (set the user-defined retention period)
.alter-merge table Prices_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable Prices_raw streaming ingestion (required for Fabric)
.alter table Prices_raw policy streamingingestion disable


//===| Recommendations |================================================================================================
// Supported datasets/versions:
// - MS CM EA reservation recommendations: 2023-05-01  -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-recommendations-ea
// - MS CM MCA reservation recommendations: 2023-05-01 -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-recommendations-mca
//======================================================================================================================

// Recommendations_raw table -- Create the table if it doesn't exist
.create-merge table Recommendations_raw ( ignore: string )

// Recommendations_raw table -- Remove all columns to allow changing column types
.alter table Recommendations_raw ( ignore: string )

// Recommendations_raw table -- Redefine all columns
.alter table Recommendations_raw (
    CostWithNoReservedInstances:        real,      // MS CM EA resv reco 2024-05-01
    CostWithNoReservedInstancesJson:    string,    // MS CM MCA resv reco 2024-05-01 -- Renamed to remove spaces and flag as JSON
    FirstUsageDate:                     datetime,  // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    InstanceFlexibilityGroup:           string,    // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    InstanceFlexibilityRatio:           real,      // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    Location:                           string,    // MS CM EA+MCA resv reco 2024-05-01
    LookBackPeriod:                     string,    // MS CM EA+MCA resv reco 2024-05-01
    MeterId:                            string,    // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    NetSavings:                         real,      // MS CM EA resv reco 2024-05-01
    NetSavingsJson:                     string,    // MS CM MCA resv reco 2024-05-01 -- Renamed to remove spaces and flag as JSON
    NormalizedSize:                     string,    // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    ProviderName:                       string,    // Hubs v1_2
    RecommendedQuantity:                real,      // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    RecommendedQuantityNormalized:      real,      // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    ResourceId:                         string,    // Hubs v1_2
    ResourceName:                       string,    // Hubs v1_2
    ResourceType:                       string,    // Hubs v1_2, MS CM EA+MCA resv reco 2024-05-01
    Scope:                              string,    // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    SKU:                                string,    // MS CM EA resv reco 2024-05-01
    SkuName:                            string,    // MS CM MCA resv reco 2024-05-01 -- Renamed to remove spaces
    SkuProperties:                      string,    // MS CM EA/MCA resv reco 2024-05-01 -- Renamed for MCA
    SubAccountId:                       string,    // Hubs v1_2
    SubAccountName:                     string,    // Hubs v1_2
    SubscriptionId:                     string,    // MS CM EA+MCA resv reco 2024-05-01
    Term:                               string,    // MS CM EA+MCA resv reco 2024-05-01
    TotalCostWithReservedInstances:     real,      // MS CM EA resv reco 2024-05-01
    TotalCostWithReservedInstancesJson: string,    // MS CM MCA resv reco 2024-05-01 -- Renamed to remove spaces and flag as JSON
    x_EffectiveCostAfter:               real,      // Hubs v1_2
    x_EffectiveCostBefore:              real,      // Hubs v1_2
    x_EffectiveCostSavings:             real,      // Hubs v1_2
    x_RecommendationCategory:           string,    // Hubs v1_2
    x_RecommendationDate:               datetime,  // Hubs v1_2
    x_RecommendationDescription:        string,    // Hubs v1_2
    x_RecommendationDetails:            dynamic,   // Hubs v1_2
    x_RecommendationId:                 string,    // Hubs v1_2
    x_ResourceGroupName:                string,    // Hubs v1_2
    x_SourceName:                       string,    // Hubs v1_0+
    x_SourceProvider:                   string,    // Hubs v1_0+
    x_SourceType:                       string,    // Hubs v1_0+
    x_SourceVersion:                    string     // Hubs v1_0+
)

// Recommendations_raw ingestion mapping
.create-or-alter table Recommendations_raw ingestion parquet mapping "Recommendations_raw_mapping"
```
[
    { "Column": "CostWithNoReservedInstances",        "Properties": { "Field": "CostWithNoReservedInstances" } },
    { "Column": "CostWithNoReservedInstancesJson",    "Properties": { "Field": "CostWithNoReservedInstancesJson" } },
    { "Column": "FirstUsageDate",                     "Properties": { "Field": "FirstUsageDate" } },
    { "Column": "InstanceFlexibilityGroup",           "Properties": { "Field": "InstanceFlexibilityGroup" } },
    { "Column": "InstanceFlexibilityRatio",           "Properties": { "Field": "InstanceFlexibilityRatio" } },
    { "Column": "Location",                           "Properties": { "Field": "Location" } },
    { "Column": "LookBackPeriod",                     "Properties": { "Field": "LookBackPeriod" } },
    { "Column": "MeterId",                            "Properties": { "Field": "MeterId" } },
    { "Column": "NetSavings",                         "Properties": { "Field": "NetSavings" } },
    { "Column": "NetSavingsJson",                     "Properties": { "Field": "NetSavingsJson" } },
    { "Column": "NormalizedSize",                     "Properties": { "Field": "NormalizedSize" } },
    { "Column": "ProviderName",                       "Properties": { "Field": "ProviderName" } },
    { "Column": "RecommendedQuantity",                "Properties": { "Field": "RecommendedQuantity" } },
    { "Column": "RecommendedQuantityNormalized",      "Properties": { "Field": "RecommendedQuantityNormalized" } },
    { "Column": "ResourceId",                         "Properties": { "Field": "ResourceId" } },
    { "Column": "ResourceName",                       "Properties": { "Field": "ResourceName" } },
    { "Column": "ResourceType",                       "Properties": { "Field": "ResourceType" } },
    { "Column": "Scope",                              "Properties": { "Field": "Scope" } },
    { "Column": "SKU",                                "Properties": { "Field": "SKU" } },
    { "Column": "SkuName",                            "Properties": { "Field": "SkuName" } },
    { "Column": "SkuProperties",                      "Properties": { "Field": "SkuProperties" } },
    { "Column": "SubAccountId",                       "Properties": { "Field": "SubAccountId" } },
    { "Column": "SubAccountName",                     "Properties": { "Field": "SubAccountName" } },
    { "Column": "SubscriptionId",                     "Properties": { "Field": "SubscriptionId" } },
    { "Column": "Term",                               "Properties": { "Field": "Term" } },
    { "Column": "TotalCostWithReservedInstances",     "Properties": { "Field": "TotalCostWithReservedInstances" } },
    { "Column": "TotalCostWithReservedInstancesJson", "Properties": { "Field": "TotalCostWithReservedInstancesJson" } },
    { "Column": "x_EffectiveCostAfter",               "Properties": { "Field": "x_EffectiveCostAfter" } },
    { "Column": "x_EffectiveCostBefore",              "Properties": { "Field": "x_EffectiveCostBefore" } },
    { "Column": "x_EffectiveCostSavings",             "Properties": { "Field": "x_EffectiveCostSavings" } },
    { "Column": "x_RecommendationCategory",           "Properties": { "Field": "x_RecommendationCategory" } },
    { "Column": "x_RecommendationDate",               "Properties": { "Field": "x_RecommendationDate" } },
    { "Column": "x_RecommendationDescription",        "Properties": { "Field": "x_RecommendationDescription" } },
    { "Column": "x_RecommendationDetails",            "Properties": { "Field": "x_RecommendationDetails" } },
    { "Column": "x_RecommendationId",                 "Properties": { "Field": "x_RecommendationId" } },
    { "Column": "x_ResourceGroupName",                "Properties": { "Field": "x_ResourceGroupName" } },
    { "Column": "x_SourceName",                       "Properties": { "Field": "x_SourceName" } },
    { "Column": "x_SourceProvider",                   "Properties": { "Field": "x_SourceProvider" } },
    { "Column": "x_SourceType",                       "Properties": { "Field": "x_SourceType" } },
    { "Column": "x_SourceVersion",                    "Properties": { "Field": "x_SourceVersion" } }
]
```

// Recommendations_raw retention policy (clear historical data)
.alter-merge table Recommendations_raw policy retention softdelete = 0d recoverability = disabled

// Recommendations_raw retention policy (set the user-defined retention period)
.alter-merge table Recommendations_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable Recommendations_raw streaming ingestion (required for Fabric)
.alter table Recommendations_raw policy streamingingestion disable


//===| Transactions |===================================================================================================
// Supported versions:
// - MS CM EA reservation transactions: 2023-05-01  -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-transactions-ea
// - MS CM MCA reservation transactions: 2023-05-01 -- See https://learn.microsoft.com/azure/cost-management-billing/dataset-schema/reservation-transactions-mca
//======================================================================================================================

// Transactions_raw table -- Create the table if it doesn't exist
.create-merge table Transactions_raw ( ignore: string )

// Transactions_raw table -- Remove all columns to allow changing column types
.alter table Transactions_raw ( ignore: string )

// Transactions_raw table -- Redefine all columns
.alter table Transactions_raw (
    AccountName:                    string,    // MS CM EA resv trans 2023-05-01
    AccountOwnerEmail:              string,    // MS CM EA resv trans 2023-05-01
    Amount:                         real,      // MS CM EA+MCA resv trans 2023-05-01
    ArmSkuName:                     string,    // MS CM EA+MCA resv trans 2023-05-01
    BillingFrequency:               string,    // MS CM EA+MCA resv trans 2023-05-01
    BillingMonth:                   string,    // MS CM EA resv trans 2023-05-01
    BillingProfileId:               string,    // MS CM MCA resv trans 2023-05-01
    BillingProfileName:             string,    // MS CM MCA resv trans 2023-05-01
    CostCenter:                     string,    // MS CM EA resv trans 2023-05-01
    Currency:                       string,    // MS CM EA+MCA resv trans 2023-05-01
    CurrentEnrollmentId:            string,    // MS CM EA resv trans 2023-05-01
    DepartmentName:                 string,    // MS CM EA resv trans 2023-05-01
    Description:                    string,    // MS CM EA+MCA resv trans 2023-05-01
    EventDate:                      datetime,  // MS CM EA+MCA resv trans 2023-05-01
    EventType:                      string,    // MS CM EA+MCA resv trans 2023-05-01
    Invoice:                        string,    // MS CM EA+MCA resv trans 2023-05-01
    InvoiceId:                      string,    // MS CM EA+MCA resv trans 2023-05-01
    InvoiceSectionId:               string,    // MS CM MCA resv trans 2023-05-01
    InvoiceSectionName:             string,    // MS CM MCA resv trans 2023-05-01
    MonetaryCommitment:             real,      // MS CM EA resv trans 2023-05-01
    Overage:                        real,      // MS CM EA resv trans 2023-05-01
    PurchasingEnrollment:           string,    // MS CM EA resv trans 2023-05-01
    PurchasingSubscriptionGuid:     string,    // MS CM EA+MCA resv trans 2023-05-01
    PurchasingSubscriptionName:     string,    // MS CM EA+MCA resv trans 2023-05-01
    Quantity:                       real,      // MS CM EA+MCA resv trans 2023-05-01
    Region:                         string,    // MS CM EA+MCA resv trans 2023-05-01
    ReservationOrderId:             string,    // MS CM EA+MCA resv trans 2023-05-01
    ReservationOrderName:           string,    // MS CM EA+MCA resv trans 2023-05-01
    Term:                           string,    // MS CM EA+MCA resv trans 2023-05-01
    x_SourceName:                   string,    // Hubs v1_0+
    x_SourceProvider:               string,    // Hubs v1_0+
    x_SourceType:                   string,    // Hubs v1_0+
    x_SourceVersion:                string     // Hubs v1_0+
)

// Transactions_raw ingestion mapping
.create-or-alter table Transactions_raw ingestion parquet mapping "Transactions_raw_mapping"
```
[
    { "Column": "AccountName",                "Properties": { "Field": "AccountName" } },
    { "Column": "AccountOwnerEmail",          "Properties": { "Field": "AccountOwnerEmail" } },
    { "Column": "Amount",                     "Properties": { "Field": "Amount" } },
    { "Column": "ArmSkuName",                 "Properties": { "Field": "ArmSkuName" } },
    { "Column": "BillingFrequency",           "Properties": { "Field": "BillingFrequency" } },
    { "Column": "BillingMonth",               "Properties": { "Field": "BillingMonth" } },
    { "Column": "BillingProfileId",           "Properties": { "Field": "BillingProfileId" } },
    { "Column": "BillingProfileName",         "Properties": { "Field": "BillingProfileName" } },
    { "Column": "CostCenter",                 "Properties": { "Field": "CostCenter" } },
    { "Column": "Currency",                   "Properties": { "Field": "Currency" } },
    { "Column": "CurrentEnrollmentId",        "Properties": { "Field": "CurrentEnrollmentId" } },
    { "Column": "DepartmentName",             "Properties": { "Field": "DepartmentName" } },
    { "Column": "Description",                "Properties": { "Field": "Description" } },
    { "Column": "EventDate",                  "Properties": { "Field": "EventDate" } },
    { "Column": "EventType",                  "Properties": { "Field": "EventType" } },
    { "Column": "Invoice",                    "Properties": { "Field": "Invoice" } },
    { "Column": "InvoiceId",                  "Properties": { "Field": "InvoiceId" } },
    { "Column": "InvoiceSectionId",           "Properties": { "Field": "InvoiceSectionId" } },
    { "Column": "InvoiceSectionName",         "Properties": { "Field": "InvoiceSectionName" } },
    { "Column": "MonetaryCommitment",         "Properties": { "Field": "MonetaryCommitment" } },
    { "Column": "Overage",                    "Properties": { "Field": "Overage" } },
    { "Column": "PurchasingEnrollment",       "Properties": { "Field": "PurchasingEnrollment" } },
    { "Column": "PurchasingSubscriptionGuid", "Properties": { "Field": "PurchasingSubscriptionGuid" } },
    { "Column": "PurchasingSubscriptionName", "Properties": { "Field": "PurchasingSubscriptionName" } },
    { "Column": "Quantity",                   "Properties": { "Field": "Quantity" } },
    { "Column": "Region",                     "Properties": { "Field": "Region" } },
    { "Column": "ReservationOrderId",         "Properties": { "Field": "ReservationOrderId" } },
    { "Column": "ReservationOrderName",       "Properties": { "Field": "ReservationOrderName" } },
    { "Column": "Term",                       "Properties": { "Field": "Term" } },
    { "Column": "x_SourceName",               "Properties": { "Field": "x_SourceName" } },
    { "Column": "x_SourceProvider",           "Properties": { "Field": "x_SourceProvider" } },
    { "Column": "x_SourceType",               "Properties": { "Field": "x_SourceType" } },
    { "Column": "x_SourceVersion",            "Properties": { "Field": "x_SourceVersion" } }
]
```

// Transactions_raw retention policy (clear historical data)
.alter-merge table Transactions_raw policy retention softdelete = 0d recoverability = disabled

// Transactions_raw retention policy (set the user-defined retention period)
.alter-merge table Transactions_raw policy retention softdelete = $$rawRetentionInDays$$d recoverability = disabled

// Disable Transactions_raw streaming ingestion (required for Fabric)
.alter table Transactions_raw policy streamingingestion disable

