@description('Optional. The location to deploy resources to.')
param location string = resourceGroup().location

@description('Required. The name of the Server Farm to create.')
param serverFarmName string

@description('Required. The name of the App Service to create.')
param appServiceName string

resource serverFarm 'Microsoft.Web/serverfarms@2025-03-01' = {
  name: serverFarmName
  location: location
  sku: {
    name: 'P0V3'
    tier: 'Premium0V3'
  }
  kind: 'linux'
  properties: {
    reserved: true
  }
}

module appService 'br/public:avm/res/web/site:0.22.0' = {
  name: '${uniqueString(deployment().name, location)}-test-app-service'
  params: {
    name: appServiceName
    kind: 'app,linux'
    serverFarmResourceId: serverFarm.id
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

@description('The resource ID of the created Server Farm.')
output serverFarmResourceId string = serverFarm.id

@description('The name of the created app service.')
output appServiceName string = appService.outputs.name

@description('The host name of the created app service.')
output appServiceHostName string = appService.outputs.defaultHostname
