targetScope = 'subscription'

metadata name = 'Using a custom host name binding'
metadata description = 'This instance deploys the module as Web App with a custom host name binding.'

// ========== //
// Parameters //
// ========== //

@description('Optional. The name of the resource group to deploy for testing purposes.')
@maxLength(90)
param resourceGroupName string = 'dep-${namePrefix}-web.sites-${serviceShort}-rg'

@description('Optional. A short identifier for the kind of deployment. Should be kept short to not run into resource-name length-constraints.')
param serviceShort string = 'wsh'

@description('Optional. A token to inject into the name of each resource.')
param namePrefix string = '#_namePrefix_#'

// Note, we enforce the location due to quota restrictions in other regions (esp. east-us)
#disable-next-line no-hardcoded-location
var enforcedLocation = 'swedencentral'
// ============ //
// Dependencies //
// ============ //

// General resources
// =================
resource resourceGroup 'Microsoft.Resources/resourceGroups@2025-04-01' = {
  name: resourceGroupName
  location: enforcedLocation
}

module nestedDependencies 'dependencies.bicep' = {
  scope: resourceGroup
  name: '${uniqueString(deployment().name, enforcedLocation)}-nestedDependencies'
  params: {
    serverFarmName: 'dep-${namePrefix}-sf-${serviceShort}'
    appServiceName: '${namePrefix}${serviceShort}1'
  }
}

// ============== //
// Test Execution //
// ============== //

@batchSize(1)
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, enforcedLocation)}-test-${serviceShort}-${iteration}'
    params: {
      name: nestedDependencies.outputs.appServiceName
      kind: 'app,linux'
      serverFarmResourceId: nestedDependencies.outputs.serverFarmResourceId
      autoGeneratedDomainNameLabelScope: 'NoReuse'
      hostNameBindings: [
        // With cert
        {
          name: nestedDependencies.outputs.appServiceHostName
          siteName: nestedDependencies.outputs.appServiceName
          sslState: 'IpBasedEnabled'
          certificate: {
            name: 'cert-${namePrefix}-${serviceShort}'
            hostNames: [nestedDependencies.outputs.appServiceHostName]
            canonicalName: nestedDependencies.outputs.appServiceHostName
          }
        }
      ]
      slots: [
        {
          name: 'slot1'
          hostNameBindings: [
            // Without cert
            {
              siteName: nestedDependencies.outputs.appServiceName
            }
          ]
        }
      ]
    }
  }
]
