#########################################################
## 'Publishing' Composite Action                   ##
#########################################################
##
## This composite action contains the logic to publish a given module to the Public Bicep Registry.
##
#########################################################
##
##-------------------------------------------##
## ACTION PARAMETERS                         ##
##-------------------------------------------##
##
##   |==============================================================================================================================================================================================================|
##   | Parameter                  | Required | Default | Description                                                                                       | Example                                                |
##   |----------------------------|----------|---------|---------------------------------------------------------------------------------------------------|--------------------------------------------------------|
##   | templateFilePath           | true     | ''      | The path to the template file to publish                                                          | 'modules/api-management/service/main.bicep'            |
##   | subscriptionId             | false    | ''      | The ID of the subscription to publish to                                                          | '11111111-1111-1111-1111-111111111111'                 |
##   |==============================================================================================================================================================================================================|
##
##---------------------------------------------##
name: "Publishing"
description: "Publishing"

inputs:
  templateFilePath:
    description: "The path to the template file to publish"
    required: true
  subscriptionId:
    description: "The ID of the subscription to publish to"
    required: false

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    # TODO: Only for testing. Should be removed in favor of public registry later
    - name: "Publish module to private bicep registry"
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          # Grouping task logs
          Write-Output '::group::Publish module to private bicep registry'

          if (-not [String]::IsNullOrEmpty('${{ inputs.subscriptionId }}')) {
            Write-Verbose ('Setting context to subscription [{0}]' -f '${{ inputs.subscriptionId }}') -Verbose
            $null = Set-AzContext -Subscription '${{ inputs.subscriptionId }}'
          }

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines'  'resourcePublish' 'Get-ModulesToPublish.ps1')
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines'  'resourcePublish' 'Get-ModulesMissingFromPrivateBicepRegistry.ps1')
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines'  'resourcePublish' 'Publish-ModuleToPrivateBicepRegistry.ps1')

          $modulesToPublish = @()

          ################################
          ##   Get modules to publish   ##
          ################################
          $functionInput = @{
            TemplateFilePath = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.templateFilePath }}"
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          # Get the modified child resources
          $modulesToPublish += Get-ModulesToPublish @functionInput -Verbose

          #############################
          ##   Get missing modules   ##
          #############################
          # Add all modules that don't exist in the target location
          $missingInputObject = @{
              TemplateFilePath    = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.templateFilePath }}"
              BicepRegistryName   = 'avmtemptesting-acr'
              BicepRegistryRgName = 'avmtemptesting-rg'
          }

          Write-Verbose "Invoke Get-ModulesMissingFromPrivateBicepRegistry with" -Verbose
          Write-Verbose ($missingInputObject | ConvertTo-Json | Out-String) -Verbose

          $missingModules = Get-ModulesMissingFromPrivateBicepRegistry @missingInputObject

          foreach($missingModule in $missingModules) {
            if($modulesToPublish.TemplateFilePath -notcontains $missingModule.TemplateFilePath) {
              $modulesToPublish += $missingModule
            }
          }

          #################
          ##   Publish   ##
          #################
          foreach ($moduleToPublish in $modulesToPublish) {
            $RelPath = (($moduleToPublish.TemplateFilePath).Split('/modules/')[-1]).Split('/main.')[0]
            Write-Output "::group::$(' - [{0}] [{1}]' -f $RelPath, $moduleToPublish.Version)"

            $functionInput = @{
              TemplateFilePath        = $moduleToPublish.TemplateFilePath
              BicepRegistryName       = 'avmtemptesting-acr'
              BicepRegistryRgName     = 'avmtemptesting-rg'
              BicepRegistryRgLocation = 'WestEurope'
              ModuleVersion           = $moduleToPublish.Version
            }

            Write-Verbose "Invoke task with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Publish-ModuleToPrivateBicepRegistry @functionInput -Verbose
          }

          Write-Output '::endgroup::'
