FROM mcr.microsoft.com/azure-powershell:ubuntu-22.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libunwind8 \
        netcat \
        ruby \
        unzip \
        dnsutils \
        nodejs

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /actions-runner

COPY InstallAgent.ps1 InstallAgent.ps1

RUN ["pwsh", "InstallAgent.ps1"]

COPY ConfigureAndRun.ps1 ConfigureAndRun.ps1

ENTRYPOINT ["pwsh"]

CMD ["ConfigureAndRun.ps1"]