@description('Specifies the location for all resources.')
param location string

@description('Used to name the Azure resources that are created')
param nameseed string

@maxLength(8)
@description('The application relevant name for the dapr component you are implementing')
param applicationEntityName string

@allowed([
  'pubsub.azure.servicebus'
  'state.azure.blobstorage'
])
@description('The DAPR application component type to configure in the Environment')
param daprComponentType string

@description('The name of the dapr component, this will be autogenerated if not provided')
param daprComponentName string = ''

@description('Names of container apps that can use this Dapr component')
param daprComponentScopes array = []

@description('Provides a default name lookup for the different dapr components')
var autoDaprComponentNameMap  = {
  'pubsub.azure.servicebus' : '${applicationEntityName}pubsub'
  'state.azure.blobstorage' : '${applicationEntityName}statestore'
}

@description('Chooses a good default name for the dapr component')
var autoDaprComponentName = empty(daprComponentName) ? autoDaprComponentNameMap[daprComponentType] : daprComponentName

module containerAppEnv 'containerAppEnv.bicep' = {
  name: 'containerAppEnv-${nameseed}'
  params: {
    location: location
    nameseed: nameseed
  }
}

module daprComponentSb 'daprComponent-sb.bicep' = if (daprComponentType=='pubsub.azure.servicebus') {
  name: 'dapr-sb-${nameseed}'
  params: {
    name: autoDaprComponentName
    location: location
    containerAppEnvName: containerAppEnv.outputs.containerAppEnvironmentName
    entityName: applicationEntityName
  }
}

module daprComponentState 'daprComponent-stor.bicep' = if (daprComponentType=='state.azure.blobstorage') {
  name: 'dapr-state-${nameseed}'
  params: {
    name: autoDaprComponentName
    location: location
    containerAppEnvName: containerAppEnv.outputs.containerAppEnvironmentName
    entityName: applicationEntityName
    scopes: daprComponentScopes
  }
}

@description('The name of the created Azure Container Apps Environment')
output containerAppEnvironmentName string = containerAppEnv.outputs.containerAppEnvironmentName

@description('The Azure Applications Insights (telemetry) instrumentation key')
output appInsightsInstrumentationKey string = containerAppEnv.outputs.appInsightsInstrumentationKey
