# Synopsis: Use a zone or geo redundant storage account
apiVersion: github.com/microsoft/PSRule/v1
kind: Rule
metadata:
  name: 'Custom.Azure.Storage.UseReplication'
spec:
  type:
  - Microsoft.Storage/storageAccounts
  condition:
    anyOf:
      - field: 'Sku.name'
        contains: 'ZRS'
      - field: 'Sku.name'
        contains: 'GRS'
