---
# Synopsis: Suppress Rules for min tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: "SuppressMin"
spec:
  rule:
    - Azure.Resource.UseTags
      # Policy specific
    - Azure.Policy.ExemptionDescriptors
    - Azure.Policy.Descriptors
    - Azure.Policy.AssignmentDescriptors
      # Cognitive Services specific
    - Azure.Cognitive.ManagedIdentity
      # Automation specific
    - Azure.Automation.ManagedIdentity
    - Azure.Automation.AuditLogs # Diagnostic Settings cannot be set by default, but require user input
    - Azure.Automation.PlatformLogs # Diagnostic Settings cannot be set by default, but require user input
      # Event Hub specific
    - Azure.EventHub.Firewall
      # Key Vault specific
    - Azure.KeyVault.Logs
    - Azure.KeyVault.Firewall
      # Traffic Manager specific
    - Azure.TrafficManager.Endpoints
    - Azure.TrafficManager.Protocol
      # Azure Load Balancer specific
    - Azure.LB.Probe
      # App Managed Environment specific
    - Azure.ContainerApp.PublicAccess
    # Azure Virtual Machine
    - Azure.VM.AMA
    - Azure.VM.MaintenanceConfig # Excluded as it requires user input
    - Azure.VM.Standalone
    # Azure App Service
    - Azure.AppService.WebProbe # Supressed as the probe path is specific to the app
    - Azure.AppService.WebProbePath # Supressed as the probe path is specific to the app
    # Azure App Configuration Store
    - Azure.AppConfig.GeoReplica # Suppressed as geo-replication is WAF requirement but not required for min
    - Azure.AppConfig.AuditLogs # Suppressed as Audit Logs are not required for min
    # Azure Front Door
    - Azure.FrontDoor.Probe # Supressed as the probe is being provided as parameter and we are not able to enforce as default value
    - Azure.FrontDoor.ProbeMethod # Supressed as the probe method is being provided as parameter and we are not able to enforce as default value
    - Azure.FrontDoor.ProbePath # Supressed as the probe path is being provided as parameter and we are not able to enforce as default value
    # Azure API Management
    - Azure.APIM.MultiRegion # Team agreed this is too expensive for most use cases and is safe to ignore. Would require dependencies for a min deployment.
    - Azure.APIM.ManagedIdentity
    # AKS specific
    - Azure.AKS.MaintenanceWindow # Excluded as it requires user input
  if:
    name: "."
    contains:
      - "min"
