---
# Synopsis: Suppress Rules for min tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: "SuppressMin"
spec:
  rule:
    - Azure.Resource.UseTags
      # Policy specific
    - Azure.Policy.ExemptionDescriptors
    - Azure.Policy.Descriptors
    - Azure.Policy.AssignmentDescriptors
      # Cognitive Services specific
    - Azure.Cognitive.ManagedIdentity
      # Automation specific
    - Azure.Automation.ManagedIdentity
      # Key Vault specific
    - Azure.KeyVault.Logs
    - Azure.KeyVault.Firewall
      # Traffic Manager specific
    - Azure.TrafficManager.Endpoints
    - Azure.TrafficManager.Protocol
      # Azure Load Balancer specific
    - Azure.LB.Probe
  if:
    name: "."
    contains:
      - "min"
