---
# Synopsis: Suppress Rules for min tests
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: "SuppressMin"
spec:
  rule:
    - Azure.Resource.UseTags
      # Policy specific
    - Azure.Policy.ExemptionDescriptors
    - Azure.Policy.Descriptors
    - Azure.Policy.AssignmentDescriptors
      # Cognitive Services specific
    - Azure.Cognitive.ManagedIdentity
      # Automation specific
    - Azure.Automation.ManagedIdentity
      # Key Vault specific
    - Azure.KeyVault.Logs
    - Azure.KeyVault.Firewall
      # Traffic Manager specific
    - Azure.TrafficManager.Endpoints
    - Azure.TrafficManager.Protocol
      # Azure Load Balancer specific
    - Azure.LB.Probe
      # App Managed Environment specific
    - Azure.ContainerApp.PublicAccess
    # Azure Virtual Machine
    - Azure.VM.AMA
    - Azure.VM.Standalone
    # Azure App Service
    - Azure.AppService.WebProbe # Supressed as the probe path is specific to the app
    - Azure.AppService.WebProbePath # Supressed as the probe path is specific to the app
  if:
    name: "."
    contains:
      - "min"
