name: AVM - Module Issue ➕🐛🔒
description: Want to request a new Module feature or report a bug? Let us know!
title: "[AVM Module Issue]: "
labels: ["Type: AVM :a: :v: :m:", "Needs: Triage :mag:"]
projects: ["Azure/566"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this AVM Module Issue!

        To help us triage your issue, please provide the below details.

        > **NOTE**: If you'd like to propose a new AVM module, please follow the process described in the [AVM repo](https://aka.ms/AVM/ModuleProposal).
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have [searched for previous/existing GitHub issues](https://aka.ms/BRM/TypeAVM) to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type?
      description: How would you best describe this issue? Is this a...
      options:
        - "Feature Request"
        - "Bug"
        - "Security Bug"
        - "I'm not sure"
    validations:
      required: true
  - type: input
    id: module-name
    attributes:
      label: Module Name
      description: Which existing AVM module is this issue related to?
      placeholder: avm-res-<rp>-<armresourcename>
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: (Optional) Module Version
      description: Please provide which version(s) of the module does this issue apply to.
    validations:
      required: false
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Please describe the issue!
    validations:
      required: true
  - type: input
    id: correlation-id
    attributes:
      label: (Optional) Correlation Id
      description: Please provide a correlation id f available and appropriate.
    validations:
      required: false
