name: AVM - Module Issue ➕🐛🔒
description: Want to request a new Module feature or report a bug? Let us know!
title: "[AVM Module Issue]: "
labels: ["Type: AVM :a: :v: :m:", "Needs: Triage :mag:"]
projects: ["Azure/566"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this AVM Module Issue! To help us triage your issue, please provide the below details.

        > **NOTE**: If you'd like to propose a new AVM module, please file an [AVM Module Proposal](https://aka.ms/AVM/ModuleProposal).
  - type: checkboxes
    id: existing-checks
    attributes:
      label: Check for previous/existing GitHub issues
      description: By submitting this issue, you confirm that you have [searched for previous/existing GitHub issues](https://aka.ms/BRM/TypeAVM) to avoid creating a duplicate.
      options:
        - label: I have checked for previous/existing GitHub issues
          required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type?
      description: How would you best describe this issue? Is this a...
      options:
        - ""
        - "Feature Request"
        - "Bug"
        - "Security Bug"
        - "I'm not sure"
    validations:
      required: true
  - type: dropdown
    id: module-name-dropdown
    attributes:
      label: Module Name
      description: Which existing AVM module is this issue related to?
      options:
        - ""
        - "avm/ptn/authorization/policy-assignment"
        - "avm/ptn/authorization/resource-role-assignment"
        - "avm/ptn/authorization/role-assignment"
        # - "avm/ptn/avd-lza/insights"
        # - "avm/ptn/avd-lza/management-plane"
        # - "avm/ptn/avd-lza/networking"
        # - "avm/ptn/avd-lza/session-hosts"
        - "avm/ptn/finops-toolkit/finops-hub"
        - "avm/ptn/policy-insights/remediation"
        - "avm/ptn/security/security-center"
        - "avm/res/aad/domain-service"
        - "avm/res/alerts-management/action-rule"
        - "avm/res/analysis-services/server"
        - "avm/res/api-management/service"
        - "avm/res/app-configuration/configuration-store"
        - "avm/res/app/container-app"
        - "avm/res/app/job"
        - "avm/res/app/managed-environment"
        - "avm/res/automation/automation-account"
        - "avm/res/batch/batch-account"
        - "avm/res/cache/redis"
        - "avm/res/cdn/profile"
        - "avm/res/cognitive-services/account"
        - "avm/res/communication/communication-service"
        - "avm/res/communication/email-service"
        - "avm/res/compute/availability-set"
        - "avm/res/compute/disk"
        - "avm/res/compute/disk-encryption-set"
        - "avm/res/compute/gallery"
        - "avm/res/compute/image"
        - "avm/res/compute/proximity-placement-group"
        - "avm/res/compute/ssh-public-key"
        - "avm/res/compute/virtual-machine"
        - "avm/res/compute/virtual-machine-scale-set"
        - "avm/res/consumption/budget"
        - "avm/res/container-instance/container-group"
        - "avm/res/container-registry/registry"
        - "avm/res/container-service/managed-cluster"
        - "avm/res/data-factory/factory"
        - "avm/res/data-protection/backup-vault"
        - "avm/res/databricks/access-connector"
        - "avm/res/databricks/workspace"
        - "avm/res/db-for-my-sql/flexible-server"
        - "avm/res/db-for-postgre-sql/flexible-server"
        - "avm/res/desktop-virtualization/application-group"
        - "avm/res/desktop-virtualization/host-pool"
        - "avm/res/desktop-virtualization/scaling-plan"
        - "avm/res/desktop-virtualization/workspace"
        - "avm/res/dev-test-lab/lab"
        - "avm/res/digital-twins/digital-twins-instance"
        - "avm/res/document-db/database-account"
        - "avm/res/event-grid/domain"
        - "avm/res/event-grid/namespace"
        - "avm/res/event-grid/system-topic"
        - "avm/res/event-grid/topic"
        - "avm/res/event-hub/namespace"
        - "avm/res/health-bot/health-bot"
        - "avm/res/healthcare-apis/workspace"
        - "avm/res/insights/action-group"
        - "avm/res/insights/activity-log-alert"
        - "avm/res/insights/component"
        - "avm/res/insights/data-collection-endpoint"
        - "avm/res/insights/data-collection-rule"
        - "avm/res/insights/diagnostic-setting"
        - "avm/res/insights/metric-alert"
        - "avm/res/insights/private-link-scope"
        - "avm/res/insights/scheduled-query-rule"
        - "avm/res/insights/webtest"
        - "avm/res/key-vault/vault"
        - "avm/res/kubernetes-configuration/extension"
        - "avm/res/kubernetes-configuration/flux-configuration"
        - "avm/res/load-test-service/load-test"
        - "avm/res/logic/workflow"
        - "avm/res/machine-learning-services/workspace"
        - "avm/res/maintenance/maintenance-configuration"
        - "avm/res/managed-identity/user-assigned-identity"
        - "avm/res/managed-services/registration-definition"
        - "avm/res/management/management-group"
        - "avm/res/net-app/net-app-account"
        - "avm/res/network/application-gateway"
        - "avm/res/network/application-gateway-web-application-firewall-policy"
        - "avm/res/network/application-security-group"
        - "avm/res/network/azure-firewall"
        - "avm/res/network/bastion-host"
        - "avm/res/network/connection"
        - "avm/res/network/ddos-protection-plan"
        - "avm/res/network/dns-forwarding-ruleset"
        - "avm/res/network/dns-resolver"
        - "avm/res/network/dns-zone"
        - "avm/res/network/express-route-circuit"
        - "avm/res/network/express-route-gateway"
        - "avm/res/network/firewall-policy"
        - "avm/res/network/front-door"
        - "avm/res/network/front-door-web-application-firewall-policy"
        - "avm/res/network/ip-group"
        - "avm/res/network/load-balancer"
        - "avm/res/network/local-network-gateway"
        - "avm/res/network/nat-gateway"
        - "avm/res/network/network-interface"
        - "avm/res/network/network-manager"
        - "avm/res/network/network-security-group"
        - "avm/res/network/network-watcher"
        - "avm/res/network/private-dns-zone"
        - "avm/res/network/private-endpoint"
        - "avm/res/network/private-link-service"
        - "avm/res/network/public-ip-address"
        - "avm/res/network/public-ip-prefix"
        - "avm/res/network/route-table"
        - "avm/res/network/service-endpoint-policy"
        - "avm/res/network/trafficmanagerprofile"
        - "avm/res/network/virtual-hub"
        - "avm/res/network/virtual-network"
        - "avm/res/network/virtual-network-gateway"
        - "avm/res/network/virtual-wan"
        - "avm/res/network/vpn-gateway"
        - "avm/res/network/vpn-site"
        - "avm/res/operational-insights/workspace"
        - "avm/res/operations-management/solution"
        - "avm/res/power-bi-dedicated/capacity"
        - "avm/res/purview/account"
        - "avm/res/recovery-services/vault"
        - "avm/res/relay/namespace"
        - "avm/res/resource-graph/query"
        - "avm/res/resources/deployment-script"
        - "avm/res/resources/resource-group"
        - "avm/res/search/search-service"
        - "avm/res/service-bus/namespace"
        - "avm/res/service-fabric/cluster"
        - "avm/res/signal-r-service/signal-r"
        - "avm/res/signal-r-service/web-pub-sub"
        - "avm/res/sql/instance-pool"
        - "avm/res/sql/managed-instance"
        - "avm/res/sql/server"
        - "avm/res/storage/storage-account"
        - "avm/res/synapse/private-link-hub"
        - "avm/res/synapse/workspace"
        - "avm/res/virtual-machine-images/image-template"
        - "avm/res/web/connection"
        - "avm/res/web/hosting-environment"
        - "avm/res/web/serverfarm"
        - "avm/res/web/site"
        - "avm/res/web/static-site"
    validations:
      required: true
  - type: input
    id: module-version
    attributes:
      label: (Optional) Module Version
      description: Please provide which version(s) of the module does this issue apply to.
    validations:
      required: false
  - type: textarea
    id: question-feedback-text
    attributes:
      label: Description
      description: Please describe the issue!
    validations:
      required: true
  - type: input
    id: correlation-id
    attributes:
      label: (Optional) Correlation Id
      description: Please provide a correlation id if available and appropriate.
    validations:
      required: false
