name: Bug Report
description: File a bug report
title: "[Bug Report]: "
labels: ["Bug Report"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: module-path
    attributes:
      label: Module path
      description: The path to the module that the bug is related to.
      placeholder: /modules/storage/storage-account
    validations:
      required: true
  - type: input
    id: bicep-version
    attributes:
      label: Bicep version
      description: The version of the Bicep CLI or Bicep VSCode extension you used when the bug happened.
      placeholder: "0.4.1008"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is vs. what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: code-snippet
    attributes:
      label: Code snippet
      description: Please copy and paste any code snippet that can help reproduce the problem.
      render: Bicep
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: Shell
