name: Module Proposal
description: Make a proposal to add a new module
title: "[Module Proposal]: "
labels: ["Module Proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Fill out this form below to suggest a new module.
  - type: dropdown
    id: exiting-module-check
    attributes:
      label: Is there a similar module?
      options:
        - Yes - answer the next question below
        - No - skip the next question below
    validations:
      required: true
  - type: textarea
    id: why-the-module
    attributes:
      label: Why is the module needed?
      description: Explain why the exiting module cannot be updated to meet your needs and why a new module must be created.
    validations:
      required: false
  - type: input
    id: module-path
    attributes:
      label: Module path
      description: The path to the new module.
      placeholder: /modules/web/function-app
    validations:
      required: true
  - type: textarea
    id: module-description
    attributes:
      label: Describe the module
      description: A clear and concise description of the module.
    validations:
      required: true
