targetScope = 'subscription'

metadata name = 'Using large parameter set'
metadata description = 'This instance deploys the module with most of its features enabled.'

// ========== //
// Parameters //
// ========== //

@description('Optional. The name of the resource group to deploy for testing purposes.')
@maxLength(90)
param resourceGroupName string = 'dep-${namePrefix}-containerregistry.registries-${serviceShort}-rg'

@description('Optional. The location to deploy resources to.')
param resourceLocation string = deployment().location

@description('Optional. A short identifier for the kind of deployment. Should be kept short to not run into resource-name length-constraints.')
param serviceShort string = 'crrmax'

@description('Optional. A token to inject into the name of each resource.')
param namePrefix string = '#_namePrefix_#'

// ============ //
// Dependencies //
// ============ //

// General resources
// =================
resource resourceGroup 'Microsoft.Resources/resourceGroups@2025-04-01' = {
  name: resourceGroupName
  location: resourceLocation
  tags: {
    SecurityControl: 'Ignore' // ignore security policies imposed on testing subscriptions
  }
}

module nestedDependencies 'dependencies.bicep' = {
  scope: resourceGroup
  name: '${uniqueString(deployment().name, resourceLocation)}-nestedDependencies'
  params: {
    // Adding base time to make the name unique as purge protection must be enabled (but may not be longer than 24 characters total)
    location: resourceLocation
    managedIdentityName: 'dep-${namePrefix}-msi-ds-${serviceShort}'
    virtualNetworkName: 'dep-${namePrefix}-vnet-${serviceShort}'
    pairedRegionScriptName: 'dep-${namePrefix}-ds-${serviceShort}'
  }
}

// Diagnostics
// ===========
module diagnosticDependencies '../../../../../../../utilities/e2e-template-assets/templates/diagnostic.dependencies.bicep' = {
  scope: resourceGroup
  name: '${uniqueString(deployment().name, resourceLocation)}-diagnosticDependencies'
  params: {
    storageAccountName: 'dep${namePrefix}diasa${serviceShort}01'
    logAnalyticsWorkspaceName: 'dep-${namePrefix}-law-${serviceShort}'
    eventHubNamespaceEventHubName: 'dep-${namePrefix}-evh-${serviceShort}'
    eventHubNamespaceName: 'dep-${namePrefix}-evhns-${serviceShort}'
    location: resourceLocation
  }
}

// ============== //
// Test Execution //
// ============== //

@batchSize(1)
module testDeployment '../../../main.bicep' = [
  for iteration in ['init', 'idem']: {
    scope: resourceGroup
    name: '${uniqueString(deployment().name, resourceLocation)}-test-${serviceShort}-${iteration}'
    params: {
      name: '${namePrefix}${serviceShort}001'
      location: resourceLocation
      acrAdminUserEnabled: false
      acrSku: 'Premium'
      autoGeneratedDomainNameLabelScope: 'SubscriptionReuse'
      roleAssignmentMode: 'AbacRepositoryPermissions'
      diagnosticSettings: [
        {
          name: 'customSetting'
          metricCategories: [
            {
              category: 'AllMetrics'
            }
          ]
          eventHubName: diagnosticDependencies.outputs.eventHubNamespaceEventHubName
          eventHubAuthorizationRuleResourceId: diagnosticDependencies.outputs.eventHubAuthorizationRuleId
          storageAccountResourceId: diagnosticDependencies.outputs.storageAccountResourceId
          workspaceResourceId: diagnosticDependencies.outputs.logAnalyticsWorkspaceResourceId
        }
      ]
      exportPolicyStatus: 'enabled'
      azureADAuthenticationAsArmPolicyStatus: 'disabled'
      softDeletePolicyStatus: 'disabled'
      softDeletePolicyDays: 7
      lock: {
        kind: 'CanNotDelete'
        name: 'myCustomLockName'
      }
      privateEndpoints: [
        {
          subnetResourceId: nestedDependencies.outputs.subnetResourceId
          privateDnsZoneGroup: {
            privateDnsZoneGroupConfigs: [
              {
                privateDnsZoneResourceId: nestedDependencies.outputs.privateDNSZoneResourceId
              }
            ]
          }
          tags: {
            'hidden-title': 'This is visible in the resource name'
            Environment: 'Non-Prod'
            Role: 'DeploymentValidation'
          }
        }
        {
          subnetResourceId: nestedDependencies.outputs.subnetResourceId
          privateDnsZoneGroup: {
            privateDnsZoneGroupConfigs: [
              {
                privateDnsZoneResourceId: nestedDependencies.outputs.privateDNSZoneResourceId
              }
            ]
          }
        }
      ]
      networkRuleSetIpRules: [
        {
          action: 'Allow'
          value: '40.74.28.0/23'
        }
      ]
      quarantinePolicyStatus: 'enabled'
      replications: [
        {
          location: nestedDependencies.outputs.pairedRegionName
          name: nestedDependencies.outputs.pairedRegionName
        }
      ]
      roleAssignments: [
        {
          name: '8f8b1c39-827f-43e6-a457-98bb15b5dbdf'
          roleDefinitionIdOrName: 'Owner'
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          name: guid('Custom seed ${namePrefix}${serviceShort}')
          roleDefinitionIdOrName: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
        {
          roleDefinitionIdOrName: subscriptionResourceId(
            'Microsoft.Authorization/roleDefinitions',
            'acdd72a7-3385-48ef-bd42-f606fba81ae7'
          )
          principalId: nestedDependencies.outputs.managedIdentityPrincipalId
          principalType: 'ServicePrincipal'
        }
      ]
      managedIdentities: {
        systemAssigned: true
        userAssignedResourceIds: [
          nestedDependencies.outputs.managedIdentityResourceId
        ]
      }
      scopeMaps: [
        {
          name: '${namePrefix}${serviceShort}ScopeMap'
          actions: [
            'repositories/*/content/read'
          ]
          description: 'A test scope map'
        }
      ]
      tokens: [
        {
          name: '${namePrefix}${serviceShort}Token'
          scopeMapResourceId: resourceId(
            subscription().subscriptionId,
            resourceGroupName,
            'Microsoft.ContainerRegistry/registries/scopeMaps',
            '${namePrefix}${serviceShort}001',
            '${namePrefix}${serviceShort}ScopeMap'
          )
          status: 'enabled'
        }
      ]
      cacheRules: [
        {
          sourceRepository: 'mcr.microsoft.com/azuredocs/aci-helloworld'
        }
        {
          name: '${namePrefix}${serviceShort}CacheRule'
          sourceRepository: 'mcr.microsoft.com/hello-world'
          targetRepository: 'cached-hello-world'
        }
      ]
      trustPolicyStatus: 'enabled'
      tasks: [
        {
          name: '${namePrefix}${serviceShort}Task1'
          platform: {
            os: 'Linux'
            architecture: 'amd64'
          }
          step: {
            type: 'EncodedTask'
            encodedTaskContent: base64('version: v1.1.0\nsteps:\n  - cmd: mcr.microsoft.com/acr/acr-cli:0.14 --help\n')
          }
          trigger: {
            timerTriggers: [
              {
                name: 'dailyTimer'
                schedule: '0 12 * * *'
                status: 'Disabled'
              }
            ]
          }
          status: 'Disabled'
        }
      ]
      webhooks: [
        {
          name: '${namePrefix}acrx001webhook'
          serviceUri: 'https://www.contoso.com/webhook'
        }
      ]
      tags: {
        'hidden-title': 'This is visible in the resource name'
        Environment: 'Non-Prod'
        Role: 'DeploymentValidation'
      }
    }
  }
]
