name: "Set Deplyoment Location"
description: "Set the deployment location for the module validation"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: "Set Deployment Location"
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |
          # Grouping task logs
          Write-Output '::group::Get Recommended Regions'

          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'sharedScripts' 'Get-AzRecommendedRegions.ps1')

          # Set fucntion input parameters
          $functionInput = @{
              excludedRegions = @("westeurope","westus2","eastus2")
              pairedRegionsOnly = $true
          }

          $regions = Get-AzRecommendedRegions @functionInput

          $index = Get-Random -Maximum ($regions.Count)

          $location = $regions[$index].Location

          Write-Verbose "Publishing output: $location" -Verbose
          Write-Output ('{0}={1}' -f 'deploymentLocation', $location) >> $env:GITHUB_OUTPUT

          Write-Output '::endgroup::'
