name: "Set Deplyoment Location"
description: "Set the deployment location for the module validation"

inputs:
  excludedRegions:
    description: "Regions to exclude from deployment"
    required: false
    default: "westeurope,westus2,eastus2"


runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: "Set Deployment Location"
      with:
          azPSVersion: "latest"
          inlineScript: |
            # Grouping task logs
            Write-Output '::group::Get Recommended Regions'

            # Load used functions
            . (Join-Path$env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'sharedScripts' 'Get-AzRecommendedRegions.ps1')

            # Set fucntion input parameters
            $functionInput = @{
                excludedRegions = ${{ inputs.excludedRegions }}
                pairedRegionsOnly = $true
            }

            $regions = Get-AzRecommendedRegions @functionInput

            $index = Get-Random -Maximum ($regions.Count)

            $location = $regions[$index].Location

            Write-Verbose "Publishing output: $deployCompressedOutput" -Verbose
            Write-Output ('{0}={1}' -f 'deploymentLocation', $location) >> $env:GITHUB_OUTPUT

            Write-Output '::endgroup::'
