---
# Synopsis: Suppress Rules for dependencies
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: 'SuppressDependency'
spec:
  if:
    name: '.'
    startsWith:
      - 'dep'
      - 'ms.'
      - 'privatelink.'
