metadata name = 'Function App Pattern'
metadata description = '''Deploys an Azure Function App together with its supporting resources: an App Service Plan, a Storage Account for the Function runtime, an Application Insights component, a Log Analytics workspace, and a User-Assigned Managed Identity used for runtime storage access. When `enableWafAlignment` is set to `true`, the module additionally configures Private Endpoints for the Function App and Storage Account, enables regional VNet integration, routes content-share traffic over the VNet, and enforces HTTPS-only / TLS 1.2 / public-access-disabled across all resources.'''
metadata owner = 'Azure/avm-ptn-web-functionapp-module-owners-bicep'

import { lockType, diagnosticSettingFullType } from 'br/public:avm/utl/types/avm-common-types:0.6.1'

// ================ //
// User-Defined     //
// Types            //
// ================ //

@export()
type privateDnsZoneResourceIdsType = {
  @description('Optional. Resource ID of the Private DNS Zone for the Function App (typically `privatelink.azurewebsites.net`).')
  sites: string?

  @description('Optional. Resource ID of the Private DNS Zone for the Storage blob endpoint (typically `privatelink.blob.core.windows.net` for Azure public cloud).')
  blob: string?

  @description('Optional. Resource ID of the Private DNS Zone for the Storage file endpoint (typically `privatelink.file.core.windows.net` for Azure public cloud).')
  file: string?

  @description('Optional. Resource ID of the Private DNS Zone for the Storage queue endpoint (typically `privatelink.queue.core.windows.net` for Azure public cloud).')
  queue: string?

  @description('Optional. Resource ID of the Private DNS Zone for the Storage table endpoint (typically `privatelink.table.core.windows.net` for Azure public cloud).')
  table: string?
}

// ================ //
// Parameters       //
// ================ //

@description('Required. The name of the Function App. Must be globally unique. Note that when `autoGeneratedDomainNameLabelScope` is set to `NoReuse`, the deployed default hostname (`<name>-<hash>.azurewebsites.net`) is longer than 60 characters; consider keeping the name short in that case.')
@minLength(2)
@maxLength(60)
param functionAppName string

@description('Optional. The Azure region into which all resources will be deployed.')
param location string = resourceGroup().location

@description('Optional. Resource tags to apply to all created resources.')
param tags object?

@description('Optional. Additional tags to apply only to the Function App resource (merged on top of `tags`). Typically used to surface the AZD service mapping via the `azd-service-name` tag.')
param functionAppTags object?

@description('Optional. Enable/Disable usage telemetry for module.')
param enableTelemetry bool = true

@description('Optional. The name of the App Service Plan to create. Defaults to `<functionAppName>-asp`.')
param appServicePlanName string = '${functionAppName}-asp'

@description('Optional. The name of the Storage Account that backs the Function App runtime. Must be globally unique, 3-24 lowercase alphanumeric characters. Defaults to a deterministic name derived from `functionAppName`. Function App names only allow alphanumeric and hyphens, so only hyphens need to be stripped to satisfy Storage Account naming constraints.')
// BCP334 fires because the linter cannot statically prove the resulting string is <= 24 chars; `take(..., 24)` enforces this at deploy time.
#disable-next-line BCP334
@maxLength(24)
param storageAccountName string = take(
  toLower('${replace(functionAppName, '-', '')}sa${uniqueString(resourceGroup().id, functionAppName)}'),
  24
)

@description('Optional. The name of the Application Insights component. Defaults to `<functionAppName>-ai`.')
param applicationInsightsName string = '${functionAppName}-ai'

@description('Optional. The name of an *existing* Log Analytics workspace (in the current resource group) to associate with Application Insights. Ignored if `logAnalyticsWorkspaceResourceId` is provided. If both are empty, a new workspace named `<functionAppName>-law` is created in the current resource group.')
param logAnalyticsWorkspaceName string = ''

@description('Optional. Resource ID of an *existing* Log Analytics workspace (anywhere in the tenant) to associate with Application Insights. When provided, takes precedence over `logAnalyticsWorkspaceName` and no workspace is created.')
param logAnalyticsWorkspaceResourceId string = ''

@description('Optional. The kind of Function App to deploy. `functionapp` (Windows) and `functionapp,linux` (Linux) are the standard values; `functionapp,linux,container` runs a custom Linux container image; `functionapp,workflowapp` is for Logic Apps Standard.')
@allowed([
  'functionapp'
  'functionapp,linux'
  'functionapp,linux,container'
  'functionapp,workflowapp'
])
param functionAppKind string = 'functionapp,linux'

@description('Optional. The SKU of the App Service Plan that hosts the Function App. Defaults to `Y1` (Consumption). For WAF-aligned deployments use `EP1` or higher to support VNet integration and zone redundancy. `FC1` (Flex Consumption) is supported by the underlying `avm/res/web/site` module but requires the consumer to also supply a compatible `functionAppConfig` (deployment storage, runtime, instance memory, max instance count) via `siteConfigOverrides` / app-settings tuned for Flex; this pattern does not yet wire that up automatically.')
@allowed([
  'Y1'
  'FC1'
  'B1'
  'B2'
  'B3'
  'S1'
  'S2'
  'S3'
  'P1v2'
  'P2v2'
  'P3v2'
  'P0v3'
  'P1v3'
  'P2v3'
  'P3v3'
  'P1mv3'
  'P2mv3'
  'P3mv3'
  'P4mv3'
  'P5mv3'
  'EP1'
  'EP2'
  'EP3'
])
param appServicePlanSkuName string = 'Y1'

@description('Optional. Number of workers for the App Service Plan.')
@minValue(1)
param appServicePlanSkuCapacity int = 1

@description('Optional. The runtime stack of the Function App, e.g. `dotnet-isolated`, `node`, `python`, `java`, `powershell`.')
@allowed([
  'dotnet'
  'dotnet-isolated'
  'java'
  'node'
  'powershell'
  'python'
])
param functionWorkerRuntime string = 'dotnet-isolated'

@description('Optional. When `true`, applies the AVM WAF-aligned baseline: regional VNet integration, HTTPS-only and TLS 1.2 enforcement, FTPS disabled, public network access disabled on the Function App and Storage Account, content share traffic routed over the VNet, geo-redundant Storage, App Service Plan zone redundancy (when SKU and capacity support it), and Private Endpoints for the Function App and Storage Account. Requires `functionAppSubnetResourceId` and `privateEndpointSubnetResourceId` to be provided. Note: this module does not provision a Key Vault — compose `avm/res/key-vault/vault` separately if you need one.')
param enableWafAlignment bool = false

@description('Optional. The resource ID of the subnet to use for Function App regional VNet integration. Required when `enableWafAlignment` is `true`.')
param functionAppSubnetResourceId string = ''

@description('Optional. The resource ID of the subnet to use for Private Endpoints. Required when `enableWafAlignment` is `true`.')
param privateEndpointSubnetResourceId string = ''

@description('Optional. Resource IDs of the Private DNS Zones to associate with the Private Endpoints created by this module when `enableWafAlignment` is `true`. Required for name resolution from the VNet to the Private Endpoints. Each property is optional — when omitted, no DNS Zone Group is configured for that Private Endpoint and consumers are expected to manage DNS resolution out-of-band (e.g., via DNS Private Resolver or Azure-provided DNS).')
param privateDnsZoneResourceIds privateDnsZoneResourceIdsType?

@description('Optional. Application settings (`name`/`value` pairs) to merge into the Function App configuration. All values must be strings; non-string values will not be projected correctly into the site `appSettings` array. Reserved keys managed by this module are silently dropped to keep the Function App in a working state — see `reservedAppSettingKeys` in `main.bicep` for the current list.')
param appSettingsKeyValuePairs object?

@description('Optional. The list of origins that are permitted to make cross-origin requests to the Function App (e.g. `https://portal.azure.com`). When non-empty, these are set as the CORS allowed origins in the site configuration.')
param corsAllowedOrigins string[] = []

@description('Optional. Whether CORS requests with credentials (cookies, authorization headers, or TLS client certificates) are allowed on the Function App. Only takes effect when `corsAllowedOrigins` is non-empty.')
param corsSupportCredentials bool = false

@description('Optional. The scope of uniqueness for the default hostname of the Function App during resource creation.')
@allowed([
  'TenantReuse'
  'SubscriptionReuse'
  'ResourceGroupReuse'
  'NoReuse'
])
param autoGeneratedDomainNameLabelScope string?

@description('Optional. The resource ID of an existing User-Assigned Managed Identity to assign to the Function App and use for runtime storage access. When not provided, a new identity is created and used.')
param userAssignedIdentityResourceId string = ''

@description('Optional. The version of the language runtime stack (e.g. `20` for Node 20, `3.11` for Python 3.11, `8.0` for .NET 8). When provided, sets `linuxFxVersion` for Linux Function Apps or the matching framework version property for Windows Function Apps. When empty AND the Function App is Linux, a sensible per-runtime default is applied (see `defaultLinuxRuntimeVersionMap` in `main.bicep`); Windows Function Apps fall back to the platform default for the chosen runtime.')
param runtimeVersion string = ''

@description('Optional. The lock settings for all resources deployed by this module.')
param lock lockType?

@description('Optional. The diagnostic settings of the Function App.')
param diagnosticSettings diagnosticSettingFullType[]?

// ================ //
// Variables        //
// ================ //

var isLinux = endsWith(functionAppKind, 'linux')

// Plan family detection.
var isConsumption = startsWith(appServicePlanSkuName, 'Y')
var isFlexConsumption = startsWith(appServicePlanSkuName, 'FC')
var isElasticPremium = startsWith(appServicePlanSkuName, 'EP')

// Function App plans need a kind that includes `functionapp`/`elastic` so the
// portal and underlying platform classify the plan correctly.
var serverFarmKind = isElasticPremium
  ? (isLinux ? 'linux,elastic' : 'elastic')
  : (isConsumption || isFlexConsumption) ? (isLinux ? 'functionapp,linux' : 'functionapp') : (isLinux ? 'linux' : 'app')

// Only Pv3, Pmv3 and EP SKUs support zone redundancy on App Service Plans, and
// ARM rejects zone-redundant plans with a worker count below 2.
var zoneRedundantEligibleSkus = [
  'P1v3'
  'P2v3'
  'P3v3'
  'P1mv3'
  'P2mv3'
  'P3mv3'
  'P4mv3'
  'P5mv3'
  'EP1'
  'EP2'
  'EP3'
]
var zoneRedundantEligible = enableWafAlignment && contains(zoneRedundantEligibleSkus, appServicePlanSkuName) && appServicePlanSkuCapacity >= 2

// Consumption (Y1) and Elastic Premium (EP*) plans require a content share for
// the Functions runtime. Dedicated/Flex plans do not.
var requiresContentShare = isConsumption || isElasticPremium

// Maps the functionWorkerRuntime value to the prefix used in linuxFxVersion (Linux Function Apps).
var linuxFxVersionPrefixMap = {
  dotnet: 'DOTNET'
  'dotnet-isolated': 'DOTNET-ISOLATED'
  java: 'JAVA'
  node: 'NODE'
  powershell: 'POWERSHELL'
  python: 'PYTHON'
}

// Sensible default Linux runtime versions used when `runtimeVersion` is empty.
// Linux Function Apps generally require a `linuxFxVersion`; without it, the app fails to start.
// These track the current GA major versions supported by the Functions host (v4).
var defaultLinuxRuntimeVersionMap = {
  dotnet: '8.0'
  'dotnet-isolated': '8.0'
  java: '17'
  node: '20'
  powershell: '7.4'
  python: '3.11'
}

var effectiveLinuxRuntimeVersion = !empty(runtimeVersion)
  ? runtimeVersion
  : defaultLinuxRuntimeVersionMap[functionWorkerRuntime]

// Maps the functionWorkerRuntime value to the matching site-config field (Windows Function Apps).
// Both `dotnet` (in-proc) and `dotnet-isolated` use `netFrameworkVersion` on Windows.
// `python` is not supported on Windows Function Apps; mapped to {} so no incorrect field is set.
var windowsRuntimeVersionConfigMap = {
  dotnet: { netFrameworkVersion: 'v${runtimeVersion}' }
  'dotnet-isolated': { netFrameworkVersion: 'v${runtimeVersion}' }
  java: { javaVersion: runtimeVersion }
  node: { nodeVersion: '~${runtimeVersion}' }
  powershell: { powerShellVersion: '~${runtimeVersion}' }
  python: {}
}

var runtimeVersionSiteConfig = isLinux
  ? { linuxFxVersion: '${linuxFxVersionPrefixMap[functionWorkerRuntime]}|${effectiveLinuxRuntimeVersion}' }
  : (!empty(runtimeVersion) ? windowsRuntimeVersionConfigMap[functionWorkerRuntime] : {})

// Resolve the Log Analytics workspace strategy:
// 1. Explicit resource ID provided -> use it as-is.
// 2. Workspace name provided (existing) -> reference it.
// 3. Otherwise -> create a new workspace (Application Insights classic mode is deprecated).
var createLogAnalyticsWorkspace = empty(logAnalyticsWorkspaceResourceId) && empty(logAnalyticsWorkspaceName)
var derivedLogAnalyticsWorkspaceName = empty(logAnalyticsWorkspaceName)
  ? '${functionAppName}-law'
  : logAnalyticsWorkspaceName

var createUserAssignedIdentity = empty(userAssignedIdentityResourceId)

// Defensive alias so safe-access (`.?`) lookups still work when the consumer passes `null` for the entire
// optional `privateDnsZoneResourceIds` parameter (rather than just omitting individual fields).
var dnsZoneIds = privateDnsZoneResourceIds ?? {}

// BYO UAMI resource ID parsing — gated by `if (!createUserAssignedIdentity)` on the `existing` reference,
// so these split lookups are only evaluated when `userAssignedIdentityResourceId` is non-empty.
var userAssignedIdentityResourceIdParts = split(userAssignedIdentityResourceId, '/')
var existingUserAssignedIdentitySubscriptionId = createUserAssignedIdentity
  ? subscription().subscriptionId
  : userAssignedIdentityResourceIdParts[2]
var existingUserAssignedIdentityResourceGroupName = createUserAssignedIdentity
  ? resourceGroup().name
  : userAssignedIdentityResourceIdParts[4]
var existingUserAssignedIdentityName = createUserAssignedIdentity ? '' : last(userAssignedIdentityResourceIdParts)

// App settings reserved by this module. User-supplied values for these keys are dropped
// (rather than allowed to override) because they would put the Function App into a broken
// or unsupported state. Surfaced via a `#warning` from `appSettingsKeyValuePairs` validation
// at compile time and listed in the parameter description.
var reservedAppSettingKeys = [
  'AzureWebJobsStorage'
  'AzureWebJobsStorage__accountName'
  'AzureWebJobsStorage__clientId'
  'AzureWebJobsStorage__credential'
  'APPLICATIONINSIGHTS_CONNECTION_STRING'
  'FUNCTIONS_EXTENSION_VERSION'
  'FUNCTIONS_WORKER_RUNTIME'
  'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
  'WEBSITE_CONTENTSHARE'
  'WEBSITE_CONTENTOVERVNET'
]

// Filter out reserved keys from user-supplied app settings so module-managed values always win.
var sanitizedUserAppSettings = reduce(
  items(appSettingsKeyValuePairs ?? {}),
  {},
  (cur, next) => contains(reservedAppSettingKeys, next.key) ? cur : union(cur, { '${next.key}': next.value })
)

// Static app settings (deploy-time known values only — safe for for-expression)
var staticAppSettings = union(
  {
    AzureWebJobsStorage__credential: 'managedidentity'
    FUNCTIONS_EXTENSION_VERSION: '~4'
    FUNCTIONS_WORKER_RUNTIME: functionWorkerRuntime
  },
  sanitizedUserAppSettings
)

var staticAppSettingsArray = [
  for setting in items(staticAppSettings): {
    name: setting.key
    value: setting.value
  }
]

// Runtime-resolved app settings shared by all plans.
var runtimeAppSettingsBase = [
  { name: 'AzureWebJobsStorage__accountName', value: storageAccount.outputs.name }
  {
    name: 'AzureWebJobsStorage__clientId'
    value: createUserAssignedIdentity
      ? userAssignedIdentity!.outputs.clientId
      : existingUserAssignedIdentity!.properties.clientId
  }
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: applicationInsights.outputs.connectionString }
]

// Content-share settings required by Consumption and Elastic Premium plans.
// These still rely on a shared-key connection string because identity-based
// content shares are not yet generally supported on those plan families.
var contentShareAppSettings = requiresContentShare
  ? [
      {
        name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
        value: storageAccount.outputs.primaryConnectionString
      }
      {
        name: 'WEBSITE_CONTENTSHARE'
        value: toLower(functionAppName)
      }
    ]
  : []

// When the storage account sits behind a Private Endpoint, the content share
// traffic must be routed over the integrated VNet (only relevant for plans
// that actually use a content share).
var contentOverVnetAppSettings = (enableWafAlignment && requiresContentShare)
  ? [
      { name: 'WEBSITE_CONTENTOVERVNET', value: '1' }
    ]
  : []

var appSettingsArray = concat(
  staticAppSettingsArray,
  runtimeAppSettingsBase,
  contentShareAppSettings,
  contentOverVnetAppSettings
)

// Resolved User-Assigned Managed Identity values (created or BYO).
var userAssignedIdentityResolvedResourceId = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.resourceId
  : userAssignedIdentityResourceId
var userAssignedIdentityPrincipalId = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.principalId
  : existingUserAssignedIdentity!.properties.principalId

// Build the final site app settings array shape expected by avm/res/web/site.
var siteConfigBase = union(
  {
    minTlsVersion: '1.2'
    ftpsState: enableWafAlignment ? 'Disabled' : 'FtpsOnly'
    http20Enabled: true
    appSettings: appSettingsArray
  },
  enableWafAlignment
    ? {
        vnetRouteAllEnabled: true
      }
    : {},
  runtimeVersionSiteConfig,
  !empty(corsAllowedOrigins)
    ? {
        cors: {
          allowedOrigins: corsAllowedOrigins
          supportCredentials: corsSupportCredentials
        }
      }
    : {}
)

// ================ //
// Telemetry        //
// ================ //

#disable-next-line no-deployments-resources
resource avmTelemetry 'Microsoft.Resources/deployments@2025-04-01' = if (enableTelemetry) {
  name: '46d3xbcp.ptn.web-functionapp.${replace('-..--..-', '.', '-')}.${substring(uniqueString(deployment().name, location), 0, 4)}'
  properties: {
    mode: 'Incremental'
    template: {
      '$schema': 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#'
      contentVersion: '1.0.0.0'
      resources: []
      outputs: {
        telemetry: {
          type: 'String'
          value: 'For more information, see https://aka.ms/avm/TelemetryInfo'
        }
      }
    }
  }
}

// ================ //
// Existing refs    //
// ================ //

resource existingLogAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2025-02-01' existing = if (!empty(logAnalyticsWorkspaceName) && empty(logAnalyticsWorkspaceResourceId)) {
  name: logAnalyticsWorkspaceName
}

resource existingUserAssignedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' existing = if (!createUserAssignedIdentity) {
  name: existingUserAssignedIdentityName
  scope: resourceGroup(existingUserAssignedIdentitySubscriptionId, existingUserAssignedIdentityResourceGroupName)
}

// ================ //
// Resources        //
// ================ //

module userAssignedIdentity 'br/public:avm/res/managed-identity/user-assigned-identity:0.5.1' = if (createUserAssignedIdentity) {
  name: take('${uniqueString(deployment().name, location)}-functionApp-uami', 64)
  params: {
    name: '${functionAppName}-uami'
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
  }
}

module logAnalyticsWorkspace 'br/public:avm/res/operational-insights/workspace:0.15.1' = if (createLogAnalyticsWorkspace) {
  name: take('${uniqueString(deployment().name, location)}-functionApp-law', 64)
  params: {
    name: derivedLogAnalyticsWorkspaceName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
  }
}

module applicationInsights 'br/public:avm/res/insights/component:0.7.1' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-ai', 64)
  params: {
    name: applicationInsightsName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    workspaceResourceId: !empty(logAnalyticsWorkspaceResourceId)
      ? logAnalyticsWorkspaceResourceId
      : (createLogAnalyticsWorkspace ? logAnalyticsWorkspace!.outputs.resourceId : existingLogAnalyticsWorkspace.id)
  }
}

module storageAccount 'br/public:avm/res/storage/storage-account:0.32.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-sa', 64)
  params: {
    name: storageAccountName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    skuName: enableWafAlignment ? 'Standard_GRS' : 'Standard_LRS'
    kind: 'StorageV2'
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
    // Identity-based access is used for the Functions runtime (`AzureWebJobsStorage__credential = managedidentity`).
    // Shared-key access is only enabled when the plan family requires a content-share connection string
    // (Y1 Consumption and EP Elastic Premium), since `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` is still the
    // GA mechanism for those plans. Dedicated and Flex plans run fully identity-based.
    allowSharedKeyAccess: requiresContentShare
    publicNetworkAccess: enableWafAlignment ? 'Disabled' : 'Enabled'
    networkAcls: enableWafAlignment
      ? {
          bypass: 'AzureServices'
          defaultAction: 'Deny'
        }
      : {
          bypass: 'AzureServices'
          defaultAction: 'Allow'
        }
    roleAssignments: [
      // Storage Blob Data Contributor – read/write access to blobs for the Function host and bindings.
      {
        roleDefinitionIdOrName: 'Storage Blob Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      // Storage Queue Data Contributor – internal queue management.
      {
        roleDefinitionIdOrName: 'Storage Queue Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      // Storage Table Data Contributor – Durable Functions / internal task hub.
      {
        roleDefinitionIdOrName: 'Storage Table Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
    ]
    // When `enableWafAlignment` is true, `privateEndpointSubnetResourceId` is required; an empty value
    // will surface as a clear ARM validation error from the underlying module rather than being silently dropped.
    privateEndpoints: enableWafAlignment
      ? [
          {
            name: 'pe-${storageAccountName}-blob'
            service: 'blob'
            subnetResourceId: privateEndpointSubnetResourceId
            privateDnsZoneGroup: !empty(dnsZoneIds.?blob)
              ? {
                  privateDnsZoneGroupConfigs: [
                    { privateDnsZoneResourceId: dnsZoneIds.?blob! }
                  ]
                }
              : null
          }
          {
            name: 'pe-${storageAccountName}-file'
            service: 'file'
            subnetResourceId: privateEndpointSubnetResourceId
            privateDnsZoneGroup: !empty(dnsZoneIds.?file)
              ? {
                  privateDnsZoneGroupConfigs: [
                    { privateDnsZoneResourceId: dnsZoneIds.?file! }
                  ]
                }
              : null
          }
          {
            name: 'pe-${storageAccountName}-queue'
            service: 'queue'
            subnetResourceId: privateEndpointSubnetResourceId
            privateDnsZoneGroup: !empty(dnsZoneIds.?queue)
              ? {
                  privateDnsZoneGroupConfigs: [
                    { privateDnsZoneResourceId: dnsZoneIds.?queue! }
                  ]
                }
              : null
          }
          {
            name: 'pe-${storageAccountName}-table'
            service: 'table'
            subnetResourceId: privateEndpointSubnetResourceId
            privateDnsZoneGroup: !empty(dnsZoneIds.?table)
              ? {
                  privateDnsZoneGroupConfigs: [
                    { privateDnsZoneResourceId: dnsZoneIds.?table! }
                  ]
                }
              : null
          }
        ]
      : null
  }
}

module appServicePlan 'br/public:avm/res/web/serverfarm:0.7.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-asp', 64)
  params: {
    name: appServicePlanName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    skuName: appServicePlanSkuName
    skuCapacity: appServicePlanSkuCapacity
    kind: serverFarmKind
    reserved: isLinux
    zoneRedundant: zoneRedundantEligible
  }
}

module functionApp 'br/public:avm/res/web/site:0.23.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-site', 64)
  params: {
    name: functionAppName
    location: location
    tags: union(tags ?? {}, functionAppTags ?? {})
    enableTelemetry: enableTelemetry
    lock: lock
    diagnosticSettings: diagnosticSettings
    kind: functionAppKind
    serverFarmResourceId: appServicePlan.outputs.resourceId
    httpsOnly: true
    managedIdentities: {
      userAssignedResourceIds: [
        userAssignedIdentityResolvedResourceId
      ]
    }
    // When `enableWafAlignment` is true, `functionAppSubnetResourceId` is required; an empty value
    // will surface as a clear ARM validation error from the underlying module rather than being silently dropped.
    virtualNetworkSubnetResourceId: enableWafAlignment ? functionAppSubnetResourceId : null
    publicNetworkAccess: enableWafAlignment ? 'Disabled' : 'Enabled'
    autoGeneratedDomainNameLabelScope: autoGeneratedDomainNameLabelScope
    siteConfig: siteConfigBase
    // When `enableWafAlignment` is true, `privateEndpointSubnetResourceId` is required; an empty value
    // will surface as a clear ARM validation error from the underlying module rather than being silently dropped.
    privateEndpoints: enableWafAlignment
      ? [
          {
            name: 'pe-${functionAppName}'
            service: 'sites'
            subnetResourceId: privateEndpointSubnetResourceId
            privateDnsZoneGroup: !empty(dnsZoneIds.?sites)
              ? {
                  privateDnsZoneGroupConfigs: [
                    { privateDnsZoneResourceId: dnsZoneIds.?sites! }
                  ]
                }
              : null
          }
        ]
      : null
  }
}

// ================ //
// Outputs          //
// ================ //

@description('The name of the resource group the resources were deployed into.')
output resourceGroupName string = resourceGroup().name

@description('The location the resources were deployed into.')
output location string = location

@description('The resource ID of the deployed Function App.')
output functionAppResourceId string = functionApp.outputs.resourceId

@description('The name of the deployed Function App.')
output functionAppName string = functionApp.outputs.name

@description('The default hostname of the deployed Function App.')
output functionAppDefaultHostname string = functionApp.outputs.defaultHostname

@description('The resource ID of the User-Assigned Managed Identity used by the Function App for runtime storage access (created by this module or supplied via `userAssignedIdentityResourceId`).')
output userAssignedIdentityResourceId string = userAssignedIdentityResolvedResourceId

@description('The principal (object) ID of the User-Assigned Managed Identity used by the Function App.')
output userAssignedIdentityPrincipalId string = userAssignedIdentityPrincipalId

@description('The client ID of the User-Assigned Managed Identity used by the Function App.')
output userAssignedIdentityClientId string = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.clientId
  : existingUserAssignedIdentity!.properties.clientId

@description('The resource ID of the App Service Plan.')
output appServicePlanResourceId string = appServicePlan.outputs.resourceId

@description('The name of the App Service Plan.')
output appServicePlanName string = appServicePlan.outputs.name

@description('The resource ID of the Storage Account that backs the Function App runtime.')
output storageAccountResourceId string = storageAccount.outputs.resourceId

@description('The name of the Storage Account that backs the Function App runtime.')
output storageAccountName string = storageAccount.outputs.name

@description('The resource ID of the Application Insights component.')
output applicationInsightsResourceId string = applicationInsights.outputs.resourceId

@description('The name of the Application Insights component.')
output applicationInsightsName string = applicationInsights.outputs.name

@description('The resource ID of the Log Analytics workspace created or referenced by this module.')
output logAnalyticsWorkspaceResourceId string = !empty(logAnalyticsWorkspaceResourceId)
  ? logAnalyticsWorkspaceResourceId
  : (createLogAnalyticsWorkspace ? logAnalyticsWorkspace!.outputs.resourceId : existingLogAnalyticsWorkspace.id)
