metadata name = 'Function App Pattern'
metadata description = '''Deploys an Azure Function App together with its supporting resources: an App Service Plan, a Storage Account for the Function runtime, an Application Insights component, a Log Analytics workspace, and a User-Assigned Managed Identity used for runtime storage access. Secure defaults are always applied (HTTPS-only, TLS 1.2 minimum, FTP/FTPS deployment disabled, no anonymous blob access, and identity-based runtime storage access wherever the selected plan family supports it). Private networking - VNet integration, Private Endpoints and Private DNS Zones - is intentionally out of scope for this module; compose the underlying AVM resource modules directly when those are required.'''
metadata owner = 'Azure/avm-ptn-app-functionapp-module-owners-bicep'

import { lockType, diagnosticSettingFullType } from 'br/public:avm/utl/types/avm-common-types:0.6.1'

// ================ //
// Parameters       //
// ================ //

@description('Required. The name of the Function App. Must be globally unique. Note that when `autoGeneratedDomainNameLabelScope` is set to `NoReuse`, the deployed default hostname (`<name>-<hash>.azurewebsites.net`) is longer than 60 characters; consider keeping the name short in that case.')
@minLength(2)
@maxLength(60)
param functionAppName string

@description('Optional. The Azure region into which all resources will be deployed.')
param location string = resourceGroup().location

@description('Optional. Resource tags to apply to all created resources.')
param tags object?

@description('Optional. Additional tags to apply only to the Function App resource (merged on top of `tags`). Typically used to surface the AZD service mapping via the `azd-service-name` tag.')
param functionAppTags object?

@description('Optional. Enable/Disable usage telemetry for module.')
param enableTelemetry bool = true

@description('Optional. The name of the App Service Plan to create. Defaults to `<functionAppName>-asp`.')
param appServicePlanName string = '${functionAppName}-asp'

@description('Optional. The name of the Storage Account that backs the Function App runtime. Must be globally unique, 3-24 lowercase alphanumeric characters. Defaults to a deterministic name derived from `functionAppName`. Function App names only allow alphanumeric and hyphens, so only hyphens need to be stripped to satisfy Storage Account naming constraints.')
// BCP334 fires because the linter cannot statically prove the resulting string is <= 24 chars; `take(..., 24)` enforces this at deploy time.
#disable-next-line BCP334
@maxLength(24)
param storageAccountName string = take(
  toLower('${replace(functionAppName, '-', '')}sa${uniqueString(resourceGroup().id, functionAppName)}'),
  24
)

@description('Optional. The name of the Application Insights component. Defaults to `<functionAppName>-ai`.')
param applicationInsightsName string = '${functionAppName}-ai'

@description('Optional. The name of an *existing* Log Analytics workspace (in the current resource group) to associate with Application Insights. Ignored if `logAnalyticsWorkspaceResourceId` is provided. If both are empty, a new workspace named `<functionAppName>-law` is created in the current resource group.')
param logAnalyticsWorkspaceName string = ''

@description('Optional. Resource ID of an *existing* Log Analytics workspace (anywhere in the tenant) to associate with Application Insights. When provided, takes precedence over `logAnalyticsWorkspaceName` and no workspace is created.')
param logAnalyticsWorkspaceResourceId string = ''

@description('Optional. The kind of Function App to deploy. `functionapp` (Windows) and `functionapp,linux` (Linux) are the standard values; `functionapp,workflowapp` is for Logic Apps Standard. Container-based Function Apps (`functionapp,linux,container`) are not yet supported by this pattern module — they require dedicated container image / registry parameters and are planned for a future release.')
@allowed([
  'functionapp'
  'functionapp,linux'
  'functionapp,workflowapp'
])
param functionAppKind string = 'functionapp,linux'

@description('Optional. The SKU of the App Service Plan that hosts the Function App. Defaults to `FC1` (Flex Consumption). When `FC1` is selected the module wires up `functionAppConfig` (identity-based deployment storage, runtime, instance memory, max instance count) on the underlying `avm/res/web/site` module automatically; Flex Consumption is Linux-only and does not support the in-process `dotnet` runtime — use `dotnet-isolated` instead.')
@allowed([
  'Y1'
  'FC1'
  'B1'
  'B2'
  'B3'
  'S1'
  'S2'
  'S3'
  'P1v2'
  'P2v2'
  'P3v2'
  'P0v3'
  'P1v3'
  'P2v3'
  'P3v3'
  'P1mv3'
  'P2mv3'
  'P3mv3'
  'P4mv3'
  'P5mv3'
  'EP1'
  'EP2'
  'EP3'
])
param appServicePlanSkuName string = 'FC1'

@description('Optional. Number of workers for the App Service Plan.')
@minValue(1)
param appServicePlanSkuCapacity int = 1

@description('Optional. Whether to spread the App Service Plan across availability zones. Only supported on Premium (`P*v2`/`P*v3`/`P*mv3`) and Elastic Premium (`EP*`) SKUs in regions that offer availability zones, and requires `appServicePlanSkuCapacity` to be at least 2. Left `false` by default because zone redundancy increases cost and is not available in every region.')
param appServicePlanZoneRedundant bool = false

@description('Optional. The runtime stack of the Function App, e.g. `dotnet-isolated`, `node`, `python`, `java`, `powershell`. Note: `dotnet` (in-process .NET) is **not** supported on Flex Consumption (`FC1`); use `dotnet-isolated` instead.')
@allowed([
  'dotnet'
  'dotnet-isolated'
  'java'
  'node'
  'powershell'
  'python'
])
param functionWorkerRuntime string = 'dotnet-isolated'

@description('Optional. (Flex Consumption only) Name of the blob container that stores the Function App\'s deployment package. Created in the runtime Storage Account when `appServicePlanSkuName` is `FC1`.')
param flexConsumptionDeploymentStorageContainerName string = 'app-package'

@description('Optional. (Flex Consumption only) Memory allocated to each instance of the Function App in MB. Allowed values are 512, 2048, and 4096.')
@allowed([
  512
  2048
  4096
])
param flexConsumptionInstanceMemoryMB int = 2048

@description('Optional. (Flex Consumption only) Maximum number of instances the Function App can scale out to. Allowed range is 40-1000.')
@minValue(40)
@maxValue(1000)
param flexConsumptionMaximumInstanceCount int = 100

@description('Optional. Application settings (`name`/`value` pairs) to merge into the Function App configuration. All values must be strings; non-string values will not be projected correctly into the site `appSettings` array. Reserved keys managed by this module are silently dropped to keep the Function App in a working state — see `reservedAppSettingKeys` in `main.bicep` for the current list.')
param appSettingsKeyValuePairs object?

@description('Optional. The list of origins that are permitted to make cross-origin requests to the Function App (e.g. `https://portal.azure.com`). When non-empty, these are set as the CORS allowed origins in the site configuration.')
param corsAllowedOrigins string[] = []

@description('Optional. Whether CORS requests with credentials (cookies, authorization headers, or TLS client certificates) are allowed on the Function App. Only takes effect when `corsAllowedOrigins` is non-empty.')
param corsSupportCredentials bool = false

@description('Optional. The scope of uniqueness for the default hostname of the Function App during resource creation.')
@allowed([
  'TenantReuse'
  'SubscriptionReuse'
  'ResourceGroupReuse'
  'NoReuse'
])
param autoGeneratedDomainNameLabelScope string?

@description('Optional. The resource ID of an existing User-Assigned Managed Identity to assign to the Function App and use for runtime storage access. When not provided, a new identity is created and used.')
param userAssignedIdentityResourceId string = ''

@description('Optional. The version of the language runtime stack (e.g. `20` for Node 20, `3.11` for Python 3.11, `8.0` for .NET 8). When provided, sets `linuxFxVersion` for Linux Function Apps or the matching framework version property for Windows Function Apps. When empty AND the Function App is Linux, a sensible per-runtime default is applied (see `defaultLinuxRuntimeVersionMap` in `main.bicep`); Windows Function Apps fall back to the platform default for the chosen runtime.')
param runtimeVersion string = ''

@description('Optional. The lock settings for all resources deployed by this module.')
param lock lockType?

@description('Optional. The diagnostic settings of the Function App.')
param diagnosticSettings diagnosticSettingFullType[]?

// ================ //
// Variables        //
// ================ //

var isLinux = endsWith(functionAppKind, 'linux')

// Plan family detection.
var isConsumption = startsWith(appServicePlanSkuName, 'Y')
var isFlexConsumption = startsWith(appServicePlanSkuName, 'FC')
var isElasticPremium = startsWith(appServicePlanSkuName, 'EP')

// Function App plans need a kind that includes `functionapp`/`elastic` so the
// portal and underlying platform classify the plan correctly.
// Flex Consumption is Linux-only and the official Microsoft sample uses bare
// `functionapp` (not `functionapp,linux`) for its plan kind, so we follow suit.
var serverFarmKind = isFlexConsumption
  ? 'functionapp'
  : isElasticPremium
      ? (isLinux ? 'linux,elastic' : 'elastic')
      : (isConsumption ? (isLinux ? 'functionapp,linux' : 'functionapp') : (isLinux ? 'linux' : 'app'))

// Consumption (Y1) and Elastic Premium (EP*) plans require a content share for
// the Functions runtime. Dedicated/Flex plans do not.
var requiresContentShare = isConsumption || isElasticPremium

// Maps the functionWorkerRuntime value to the prefix used in linuxFxVersion (Linux Function Apps).
var linuxFxVersionPrefixMap = {
  dotnet: 'DOTNET'
  'dotnet-isolated': 'DOTNET-ISOLATED'
  java: 'JAVA'
  node: 'NODE'
  powershell: 'POWERSHELL'
  python: 'PYTHON'
}

// Sensible default Linux runtime versions used when `runtimeVersion` is empty.
// Linux Function Apps generally require a `linuxFxVersion`; without it, the app fails to start.
// These track the current GA major versions supported by the Functions host (v4).
var defaultLinuxRuntimeVersionMap = {
  dotnet: '8.0'
  'dotnet-isolated': '8.0'
  java: '17'
  node: '20'
  powershell: '7.4'
  python: '3.11'
}

var effectiveLinuxRuntimeVersion = !empty(runtimeVersion)
  ? runtimeVersion
  : defaultLinuxRuntimeVersionMap[functionWorkerRuntime]

// Maps the functionWorkerRuntime value to the matching site-config field (Windows Function Apps).
// Both `dotnet` (in-proc) and `dotnet-isolated` use `netFrameworkVersion` on Windows.
// `python` is not supported on Windows Function Apps; mapped to {} so no incorrect field is set.
var windowsRuntimeVersionConfigMap = {
  dotnet: { netFrameworkVersion: 'v${runtimeVersion}' }
  'dotnet-isolated': { netFrameworkVersion: 'v${runtimeVersion}' }
  java: { javaVersion: runtimeVersion }
  node: { nodeVersion: '~${runtimeVersion}' }
  powershell: { powerShellVersion: '~${runtimeVersion}' }
  python: {}
}

var runtimeVersionSiteConfig = isFlexConsumption
  // Flex Consumption advertises the runtime via `functionAppConfig.runtime` (set below) — setting
  // `linuxFxVersion` on the site config is not supported and would conflict with that contract.
  ? {}
  : (isLinux
      ? { linuxFxVersion: '${linuxFxVersionPrefixMap[functionWorkerRuntime]}|${effectiveLinuxRuntimeVersion}' }
      : (!empty(runtimeVersion) ? windowsRuntimeVersionConfigMap[functionWorkerRuntime] : {}))

// Resolve the Log Analytics workspace strategy:
// 1. Explicit resource ID provided -> use it as-is.
// 2. Workspace name provided (existing) -> reference it.
// 3. Otherwise -> create a new workspace (Application Insights classic mode is deprecated).
var createLogAnalyticsWorkspace = empty(logAnalyticsWorkspaceResourceId) && empty(logAnalyticsWorkspaceName)
var derivedLogAnalyticsWorkspaceName = empty(logAnalyticsWorkspaceName)
  ? '${functionAppName}-law'
  : logAnalyticsWorkspaceName

var createUserAssignedIdentity = empty(userAssignedIdentityResourceId)

// BYO UAMI resource ID parsing — gated by `if (!createUserAssignedIdentity)` on the `existing` reference,
// so these split lookups are only evaluated when `userAssignedIdentityResourceId` is non-empty.
var userAssignedIdentityResourceIdParts = split(userAssignedIdentityResourceId, '/')
var existingUserAssignedIdentitySubscriptionId = createUserAssignedIdentity
  ? subscription().subscriptionId
  : userAssignedIdentityResourceIdParts[2]
var existingUserAssignedIdentityResourceGroupName = createUserAssignedIdentity
  ? resourceGroup().name
  : userAssignedIdentityResourceIdParts[4]
var existingUserAssignedIdentityName = createUserAssignedIdentity ? '' : last(userAssignedIdentityResourceIdParts)

// App settings reserved by this module. User-supplied values for these keys are dropped
// (rather than allowed to override) because they would put the Function App into a broken
// or unsupported state. Surfaced via a `#warning` from `appSettingsKeyValuePairs` validation
// at compile time and listed in the parameter description.
var reservedAppSettingKeys = [
  'AzureWebJobsStorage'
  'AzureWebJobsStorage__accountName'
  'AzureWebJobsStorage__clientId'
  'AzureWebJobsStorage__credential'
  'APPLICATIONINSIGHTS_CONNECTION_STRING'
  'FUNCTIONS_EXTENSION_VERSION'
  'FUNCTIONS_WORKER_RUNTIME'
  'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
  'WEBSITE_CONTENTSHARE'
]

// Filter out reserved keys from user-supplied app settings so module-managed values always win.
var sanitizedUserAppSettings = reduce(
  items(appSettingsKeyValuePairs ?? {}),
  {},
  (cur, next) => contains(reservedAppSettingKeys, next.key) ? cur : union(cur, { '${next.key}': next.value })
)

// Static app settings (deploy-time known values only — safe for for-expression).
// On Flex Consumption, `FUNCTIONS_EXTENSION_VERSION` and `FUNCTIONS_WORKER_RUNTIME` must NOT be set
// as app settings — they are managed via `functionAppConfig.runtime` and adding them would conflict.
var staticAppSettings = isFlexConsumption
  ? union(
      {
        AzureWebJobsStorage__credential: 'managedidentity'
      },
      sanitizedUserAppSettings
    )
  : union(
      {
        AzureWebJobsStorage__credential: 'managedidentity'
        FUNCTIONS_EXTENSION_VERSION: '~4'
        FUNCTIONS_WORKER_RUNTIME: functionWorkerRuntime
      },
      sanitizedUserAppSettings
    )

var staticAppSettingsArray = [
  for setting in items(staticAppSettings): {
    name: setting.key
    value: setting.value
  }
]

// Runtime-resolved app settings shared by all plans.
var runtimeAppSettingsBase = [
  { name: 'AzureWebJobsStorage__accountName', value: storageAccount.outputs.name }
  {
    name: 'AzureWebJobsStorage__clientId'
    value: createUserAssignedIdentity
      ? userAssignedIdentity!.outputs.clientId
      : existingUserAssignedIdentity!.properties.clientId
  }
  { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: applicationInsights.outputs.connectionString }
]

// Content-share settings required by Consumption and Elastic Premium plans.
// These still rely on a shared-key connection string because identity-based
// content shares are not yet generally supported on those plan families.
var contentShareAppSettings = requiresContentShare
  ? [
      {
        name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
        value: storageAccount.outputs.primaryConnectionString
      }
      {
        name: 'WEBSITE_CONTENTSHARE'
        value: toLower(functionAppName)
      }
    ]
  : []

var appSettingsArray = concat(
  staticAppSettingsArray,
  runtimeAppSettingsBase,
  contentShareAppSettings
)

// Resolved User-Assigned Managed Identity values (created or BYO).
var userAssignedIdentityResolvedResourceId = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.resourceId
  : userAssignedIdentityResourceId
var userAssignedIdentityPrincipalId = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.principalId
  : existingUserAssignedIdentity!.properties.principalId

// Build the final site app settings array shape expected by avm/res/web/site.
// The security-relevant values here are always applied — they are baseline hardening
// rather than an opt-in feature: TLS 1.2 minimum and no FTP/FTPS publishing surface.
var siteConfigBase = union(
  {
    minTlsVersion: '1.2'
    ftpsState: 'Disabled'
    http20Enabled: true
    appSettings: appSettingsArray
  },
  runtimeVersionSiteConfig,
  !empty(corsAllowedOrigins)
    ? {
        cors: {
          allowedOrigins: corsAllowedOrigins
          supportCredentials: corsSupportCredentials
        }
      }
    : {}
)

// `functionAppConfig` is the Flex Consumption-specific contract on Microsoft.Web/sites that wires up
// identity-based deployment storage, runtime selection and scale/concurrency. Only emitted for FC1
// — for every other plan family it stays `null` so the underlying site module skips the property.
// The `dotnet` (in-process .NET) runtime is intentionally not mapped because Flex Consumption only
// supports `dotnet-isolated`; selecting `dotnet` with `FC1` will surface as a clear ARM validation
// error from the underlying `Microsoft.Web/sites` resource.
var flexConsumptionFunctionAppConfig = {
  deployment: {
    storage: {
      type: 'blobContainer'
      value: '${storageAccount.outputs.primaryBlobEndpoint}${flexConsumptionDeploymentStorageContainerName}'
      authentication: {
        type: 'UserAssignedIdentity'
        userAssignedIdentityResourceId: userAssignedIdentityResolvedResourceId
      }
    }
  }
  runtime: {
    name: functionWorkerRuntime
    version: effectiveLinuxRuntimeVersion
  }
  scaleAndConcurrency: {
    instanceMemoryMB: flexConsumptionInstanceMemoryMB
    maximumInstanceCount: flexConsumptionMaximumInstanceCount
  }
}

// ================ //
// Telemetry        //
// ================ //

#disable-next-line no-deployments-resources
resource avmTelemetry 'Microsoft.Resources/deployments@2025-04-01' = if (enableTelemetry) {
  name: '46d3xbcp.ptn.app-functionapp.${replace('-..--..-', '.', '-')}.${substring(uniqueString(deployment().name, location), 0, 4)}'
  properties: {
    mode: 'Incremental'
    template: {
      '$schema': 'https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#'
      contentVersion: '1.0.0.0'
      resources: []
      outputs: {
        telemetry: {
          type: 'String'
          value: 'For more information, see https://aka.ms/avm/TelemetryInfo'
        }
      }
    }
  }
}

// ================ //
// Existing refs    //
// ================ //

resource existingLogAnalyticsWorkspace 'Microsoft.OperationalInsights/workspaces@2025-02-01' existing = if (!empty(logAnalyticsWorkspaceName) && empty(logAnalyticsWorkspaceResourceId)) {
  name: logAnalyticsWorkspaceName
}

resource existingUserAssignedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' existing = if (!createUserAssignedIdentity) {
  name: existingUserAssignedIdentityName
  scope: resourceGroup(existingUserAssignedIdentitySubscriptionId, existingUserAssignedIdentityResourceGroupName)
}

// ================ //
// Resources        //
// ================ //

module userAssignedIdentity 'br/public:avm/res/managed-identity/user-assigned-identity:0.6.0' = if (createUserAssignedIdentity) {
  name: take('${uniqueString(deployment().name, location)}-functionApp-uami', 64)
  params: {
    name: '${functionAppName}-uami'
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
  }
}

module logAnalyticsWorkspace 'br/public:avm/res/operational-insights/workspace:0.16.1' = if (createLogAnalyticsWorkspace) {
  name: take('${uniqueString(deployment().name, location)}-functionApp-law', 64)
  params: {
    name: derivedLogAnalyticsWorkspaceName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
  }
}

module applicationInsights 'br/public:avm/res/insights/component:0.8.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-ai', 64)
  params: {
    name: applicationInsightsName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    workspaceResourceId: !empty(logAnalyticsWorkspaceResourceId)
      ? logAnalyticsWorkspaceResourceId
      : (createLogAnalyticsWorkspace ? logAnalyticsWorkspace!.outputs.resourceId : existingLogAnalyticsWorkspace.id)
  }
}

module storageAccount 'br/public:avm/res/storage/storage-account:0.33.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-sa', 64)
  params: {
    name: storageAccountName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    skuName: 'Standard_LRS'
    kind: 'StorageV2'
    // Flex Consumption Function Apps deploy from a blob container in the runtime Storage Account
    // referenced via `functionAppConfig.deployment.storage`. Create that container up-front so the
    // Function App's first deployment doesn't fail. Soft-delete defaults are kept aligned with the
    // storage module's defaults so non-Flex plan families behave the same as before.
    blobServices: {
      containerDeleteRetentionPolicyEnabled: true
      containerDeleteRetentionPolicyDays: 7
      deleteRetentionPolicyEnabled: true
      deleteRetentionPolicyDays: 6
      containers: isFlexConsumption
        ? [
            {
              name: flexConsumptionDeploymentStorageContainerName
              publicAccess: 'None'
            }
          ]
        : null
    }
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
    // Identity-based access is used for the Functions runtime (`AzureWebJobsStorage__credential = managedidentity`).
    // Shared-key access is only enabled when the plan family requires a content-share connection string
    // (Y1 Consumption and EP Elastic Premium), since `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` is still the
    // GA mechanism for those plans. Dedicated and Flex plans run fully identity-based.
    allowSharedKeyAccess: requiresContentShare
    publicNetworkAccess: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      defaultAction: 'Allow'
    }
    roleAssignments: [
      // Storage Blob Data Contributor – read/write access to blobs for the Function host and bindings.
      {
        roleDefinitionIdOrName: 'Storage Blob Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      // Storage Queue Data Contributor – internal queue management.
      {
        roleDefinitionIdOrName: 'Storage Queue Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
      // Storage Table Data Contributor – Durable Functions / internal task hub.
      {
        roleDefinitionIdOrName: 'Storage Table Data Contributor'
        principalId: userAssignedIdentityPrincipalId
        principalType: 'ServicePrincipal'
      }
    ]
  }
}

module appServicePlan 'br/public:avm/res/web/serverfarm:0.7.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-asp', 64)
  params: {
    name: appServicePlanName
    location: location
    tags: tags
    enableTelemetry: enableTelemetry
    lock: lock
    skuName: appServicePlanSkuName
    skuCapacity: appServicePlanSkuCapacity
    kind: serverFarmKind
    reserved: isLinux
    // Passed explicitly because the underlying serverfarm module defaults this to `true` for
    // Premium and Elastic Premium SKUs, which fails to deploy unless the worker count is at
    // least 2. Zone redundancy stays an explicit, opt-in choice for the consumer instead.
    zoneRedundant: appServicePlanZoneRedundant
  }
}

module functionApp 'br/public:avm/res/web/site:0.24.0' = {
  name: take('${uniqueString(deployment().name, location)}-functionApp-site', 64)
  params: {
    name: functionAppName
    location: location
    tags: union(tags ?? {}, functionAppTags ?? {})
    enableTelemetry: enableTelemetry
    lock: lock
    diagnosticSettings: diagnosticSettings
    kind: functionAppKind
    serverFarmResourceId: appServicePlan.outputs.resourceId
    httpsOnly: true
    managedIdentities: {
      userAssignedResourceIds: [
        userAssignedIdentityResolvedResourceId
      ]
    }
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: autoGeneratedDomainNameLabelScope
    siteConfig: siteConfigBase
    // `functionAppConfig` is only set for Flex Consumption (`FC1`); the underlying site module
    // ignores `null`, leaving non-Flex plan families on their existing app-settings-driven contract.
    functionAppConfig: isFlexConsumption ? flexConsumptionFunctionAppConfig : null
  }
}

// ================ //
// Outputs          //
// ================ //

@description('The name of the resource group the resources were deployed into.')
output resourceGroupName string = resourceGroup().name

@description('The location the resources were deployed into.')
output location string = location

@description('The resource ID of the deployed Function App.')
output functionAppResourceId string = functionApp.outputs.resourceId

@description('The name of the deployed Function App.')
output functionAppName string = functionApp.outputs.name

@description('The default hostname of the deployed Function App.')
output functionAppDefaultHostname string = functionApp.outputs.defaultHostname

@description('The resource ID of the User-Assigned Managed Identity used by the Function App for runtime storage access (created by this module or supplied via `userAssignedIdentityResourceId`).')
output userAssignedIdentityResourceId string = userAssignedIdentityResolvedResourceId

@description('The principal (object) ID of the User-Assigned Managed Identity used by the Function App.')
output userAssignedIdentityPrincipalId string = userAssignedIdentityPrincipalId

@description('The client ID of the User-Assigned Managed Identity used by the Function App.')
output userAssignedIdentityClientId string = createUserAssignedIdentity
  ? userAssignedIdentity!.outputs.clientId
  : existingUserAssignedIdentity!.properties.clientId

@description('The resource ID of the App Service Plan.')
output appServicePlanResourceId string = appServicePlan.outputs.resourceId

@description('The name of the App Service Plan.')
output appServicePlanName string = appServicePlan.outputs.name

@description('The resource ID of the Storage Account that backs the Function App runtime.')
output storageAccountResourceId string = storageAccount.outputs.resourceId

@description('The name of the Storage Account that backs the Function App runtime.')
output storageAccountName string = storageAccount.outputs.name

@description('The resource ID of the Application Insights component.')
output applicationInsightsResourceId string = applicationInsights.outputs.resourceId

@description('The name of the Application Insights component.')
output applicationInsightsName string = applicationInsights.outputs.name

@description('The resource ID of the Log Analytics workspace created or referenced by this module.')
output logAnalyticsWorkspaceResourceId string = !empty(logAnalyticsWorkspaceResourceId)
  ? logAnalyticsWorkspaceResourceId
  : (createLogAnalyticsWorkspace ? logAnalyticsWorkspace!.outputs.resourceId : existingLogAnalyticsWorkspace.id)
