name: BRM / Automaticly Triggered BRM Generation

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync main
        uses: actions/checkout@v2.3.4
        with:
          ref: main
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }} # A PAT must be used to re-trigger workflows after commit

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }} # A PAT must be used to re-trigger workflows after commit

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run prettier --write .

      - uses: EndBug/add-and-commit@v9
        if: steps.tag_version.outputs.release_type
        with:
          message: Update Version to ${{ steps.tag_version.outputs.new_version }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .github

      - name: Commit Changes
        run: |
          git config --global user.email "auto-brm@noreply.github.com"
          git config --global user.name "Auto brm"

          git add .

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Autoformat with BRM"
            git push
          fi
