name: "avm.res.key-vault.vault"

on:
  workflow_dispatch:
    inputs:
      staticValidation:
        type: boolean
        description: "Execute static validation"
        required: false
        default: true
      deploymentValidation:
        type: boolean
        description: "Execute deployment validation"
        required: false
        default: true
      removeDeployment:
        type: boolean
        description: "Remove deployed module"
        required: false
        default: true
      customLocation:
        type: string
        description: "Default location overwrite (e.g., eastus)"
        required: false
  push:
    branches:
      # - main
      - users/alsehr/bu_calculatedPipelineStages
    paths:
      - ".github/actions/templates/avm-**"
      - ".github/workflows/avm.template.module.yml"
      - ".github/workflows/avm.res.key-vault.vault.yml"
      - "avm/res/key-vault/vault/**"
      - "avm/utilities/pipelines/**"

  pull_request:
    branches:
      # - main
      - users/alsehr/bu_calculatedPipelineStages
    paths:
      - ".github/actions/templates/avm-**"
      - ".github/workflows/avm.template.module.yml"
      - ".github/workflows/avm.res.key-vault.vault.yml"
      - "avm/res/key-vault/vault/**"
      - "avm/utilities/pipelines/**"
      - "!avm/utilities/pipelines/platform/**"
      - "!*/**/README.md"

env:
  modulePath: "avm/res/key-vault/vault"
  workflowPath: ".github/workflows/avm.res.key-vault.vault.yml"

concurrency:
  group: ${{ github.workflow }}

jobs:
  ###########################
  #   Initialize pipeline   #
  ###########################
  job_initialize_pipeline:
    runs-on: ubuntu-latest
    name: "Initialize pipeline"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Get calculated job controls"
        id: get-calculated-job-controls
        uses: ./.github/actions/templates/avm-getCalculatedJobControls
        with:
          workflowPath: "${{ env.workflowPath}}"
      - name: "Get module test file paths"
        id: get-module-test-file-paths
        uses: ./.github/actions/templates/avm-getModuleTestFiles
        with:
          modulePath: "${{ env.modulePath }}"
    outputs:
      moduleTestFilePaths: ${{ steps.get-module-test-file-paths.outputs.moduleTestFilePaths }}
      calculatedJobControls : ${{ steps.get-calculated-job-controls.outputs.calculatedJobControls }}
      psRuleModuleTestFilePaths: ${{ steps.get-module-test-file-paths.outputs.psRuleModuleTestFilePaths }}
      modulePath: "${{ env.modulePath }}"

  ##############################
  #   Call reusable workflow   #
  ##############################
  call-workflow-passing-data:
    name: "Run"
    permissions:
      id-token: write # For OIDC
      contents: write # For release tags
    needs:
      - job_initialize_pipeline
    uses: ./.github/workflows/avm.template.module.yml
    with:
      moduleTestFilePaths: "${{ needs.job_initialize_pipeline.outputs.moduleTestFilePaths }}"
      calculatedJobControls : "${{ needs.job_initialize_pipeline.outputs.calculatedJobControls }}"
      psRuleModuleTestFilePaths: "${{ needs.job_initialize_pipeline.outputs.psRuleModuleTestFilePaths }}"
      modulePath: "${{ needs.job_initialize_pipeline.outputs.modulePath}}"
    secrets: inherit
