name: .Platform - Sync AVM module list

on:
  schedule:
    - cron: "30 4 * * *" # Every day at 4:30 am
  workflow_dispatch:

jobs:
  sync-avm-modules-list:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TEAM_LINTER_APP_ID }}
          private_key: ${{ secrets.TEAM_LINTER_PRIVATE_KEY }}
      - name: sync avm modules list
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'avm' 'utilities' 'pipelines' 'platform' 'Sync-AvmModulesList.ps1')

          $functionInput = @{
            Repo     = "${{ github.repository_owner }}/${{ github.event.repository.name }}"
            RepoRoot = $env:GITHUB_WORKSPACE
          }

          Sync-AvmModulesList @functionInput -Verbose
