# .github/workflows/minimal-toggle-test.yml
name: Minimal Toggle Test

on:
  workflow_dispatch:
    inputs:
      targetState:
        type: choice
        description: "Enable or disable workflows"
        required: true
        options:
          - "Enable"
          - "Disable"
        default: "Disable"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: echo "Target state is ${{ inputs.targetState }}"
