name: .Platform - Create Changelog

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - "*/**/README.md"
  push:
      paths: "*/**/README.md"

jobs:
  changelog:
    runs-on: ubuntu-latest

    # TODO
    # - if the PR contains a README.md file, it will run the job and require the CHANGELOG.md change in the same dir
    # - if there is a breaking change (and the version is > 1.0.0), it requires the major version to be bumped

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}

      - name: Check for README.md and CHANGELOG.md
        id: check_files
        run: |
          file_paths=$(git diff --name-only --merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -i 'README.md\|CHANGELOG.md')
          echo $file_paths
          if [ -z "$file_paths" ]; then
            echo "No README.md or CHANGELOG.md files found in the PR"
            exit 1
          fi
          file_paths_array=($file_paths)
          echo "file_array='${file_paths_array[@]}'" >> $GITHUB_ENV

      - name: Update Changelog
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Load used functions
          . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'publish' 'Set-ModuleChangelog.ps1')

          $functionInput = @{
            Files = $env:file_array
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Set-ModuleChangelog @functionInput -Verbose
