name: .Platform - Create Changelog

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      - "*/**/README.md"

jobs:
  create-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check for README.md
        id: check_readme
        run: |
          readme_path=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -i 'README.md' || true)
          echo "::set-output name=readme_path::$readme_path"

    # - name: Modify file
    #   run: |
    #     echo "New content" >> file.txt

    # - name: Commit changes
    #   run: |
    #     git config --global user.name 'github-actions[bot]'
    #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    #     git add file.txt
    #     git commit -m "Update file.txt"
    #     git push
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
