name: BRM / Automaticly Format Workflow Files

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.WORKFLOW_PAT }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          token: ${{ secrets.WORKFLOW_PAT }} # A WORKFLOW_PAT must be used to re-trigger workflows after commit. This PAT must have the workflow scope. This is not generally recommended.

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run prettier --write .github

      - uses: EndBug/add-and-commit@v9
        with:
          message: Autogenerate Bicep Files
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: .github
