name: Validate module

on:
  pull_request:
    branches: [main]

jobs:
  prerequisite:
    runs-on: ubuntu-latest
    outputs:
      changed_module_dir: ${{ steps.check-for-module-changes.outputs.result }}
    steps:
      - name: Check for module changes
        uses: actions/github-script@v5
        id: check-for-module-changes
        with:
          result-encoding: string
          script: |
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
            })

            const path = require("path")
            const moduleDirs = [...new Set(files
              .filter(x => x.filename.startsWith("modules/"))
              .map(x => {
                const dirs = path.dirname(x.filename)
                const segments = dirs.split("/").slice(0, 3)
                return segments.join("/")
              }))]

            switch (moduleDirs.length) {
              case 0:
                console.log("No module changes found.")
                return ""
              case 1:
                console.log(`Found 1 changed module: ${moduleDirs[0]}`)
                return moduleDirs[0]
              default:
                console.log("Found more than one changed modules:")
                moduleDirs.forEach((moduleDir) => console.log(`- ${moduleDir}`))
                core.setFailed("Only one module can be added or updated at a time.")
            }

  main:
    runs-on: ubuntu-latest
    needs: prerequisite
    if: needs.prerequisite.outputs.changed_module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # TODO: remove once brm is published
      - name: Install Bicep registry module tool
        run: dotnet tool install -g --add-source ./packages Bicep.RegistryModuleTool
      
      - name: Show Bicep version
        run: bicep --version

      - name: Validate module files
        run: brm validate --verbose
        working-directory: ${{ needs.prerequisite.outputs.changed_module_dir }}

      # TODO: deployment test
