name: Validate module

on:
  pull_request:
    branches:
      - main

jobs:
  prerequisite:
    uses: Azure/bicep-registry-modules/.github/workflows/get-changed-module.yml@main

  main:
    runs-on: ubuntu-latest
    needs: prerequisite
    if: needs.prerequisite.outputs.changed_module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # TODO: remove once brm is published
      - name: Install Bicep registry module tool
        run: dotnet tool install -g --add-source ./packages Bicep.RegistryModuleTool

      - name: Validate module files
        run: brm validate
        working-directory: ${{ needs.prerequisite.outputs.changed_module_dir }}

      # TODO: deployment test
